### ISSUE TITLE
Description of IDAT, filter type, scanline data unclear

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#10]
Raised by: Björn Höhrmann
Originally raised: [04 Mar 2011](https://lists.w3.org/Archives/Public/png-group/2011Mar/0000.html)

>   Regarding <http://www.w3.org/TR/2003/REC-PNG-20031110>, in the process
of implementing an IDAT recompressor I've implemented parts of the PNG
specification. In this I found three things hard to understand. The
first thing is how IDAT chunks encode filter type and the scanline data.
This is mentioned in passing somewhere, but it is not as clear as, say,
some indented

```
  +-------------+------------------------------------+
  | Filter type | Filtered data for this scanline... |
  +-------------+------------------------------------+
```

**Comment by svgeesus** [comment]
To be honest, this seems entirely clear in the spec at present. In particular, the ascii-art diagram in the original report looks just like 

Figure 4.9 — Serializing and filtering a scanline

in [4.5.4 Filtering](https://w3c.github.io/PNG-spec/#4Concepts.EncodingFiltering)

which has the filter type at the start followed by the filtered data for that scanline.

**Comment by Crissov** [comment]
JFTR CC @hoehrmann

**Comment by ProgramMax** [comment]
In addition to Figure 4.9, there is the text "...the byte sequence in a scanline to an equal length sequence of bytes preceded by a filter type byte...".


So I think that part of Björn Höhrmann's comment is covered. I'll close this.
Note that the original comment had 3 parts and only the first part is mentioned here. The other parts are covered in #11 and #12.
