### ISSUE TITLE
Remove hard-coded section numbers

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#106]
A lot of hard-coded section numbers are now incorrect because of the way ReSpec wants to starts its sections.

For example, "See 6.1: Colour types and values". It is now 7.1.

Rather than hard-code the section numbers, this should link to the section name like [[[#section-name]]]. ReSpec will then include the section numbers it generated.

(Many of these hard-coded section numbers can be found just by searching for "see".)

**Comment by svgeesus** [comment]
I agree that manually maintaining these numbers is additional and not useful effort.
