### ISSUE TITLE
Filter description unclear

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#11]
Raised by: Björn Höhrmann
Originally raised: [04 Mar 2011](https://lists.w3.org/Archives/Public/png-group/2011Mar/0000.html)

> The second thing is the discussion of filters. Filters map from source
to destination, but section 9.2 isn't quite phrased this way. It's hard
to properly understand the "pixel versus byte" distinction early on in
the section, and the notation in table 9.1 is hard to understand. I got
confused a couple of times in what order things had to be done, what it
really means to have `Filt(x)` in the reconstruction function and so on.

> One ambiguity for instance is that it's not really clear what `Orig(x)`
is since from the perspective of the scanline for `x` there are two
original values for the other variables, before and after they had their
filter applied. The same goes for `Recon(a)`, is that before or after it
had its scanline filter removed? While I figured out the answer, I did
understand these things incorrectly initially.

> (It would have helped a lot had there been some pseudo-code showing how
you get from the color and depth values to the advance width and how you
resolve the aforementioned ambiguity, or at the least something about
how you can decode top-down but need to encode bottom-up or with a separate buffer.)

**Comment by svgeesus** [comment]
Yes this could at minimum do with a diagram showing two or three scanlines in 

1. the original image
2. the filtered image
3. the reconstructed image.

This would help to graphically illustrate the somewhat convoluted

> the byte corresponding to x in the pixel immediately before the pixel containing x

**Comment by ProgramMax** [comment]
This seems to have multiple parts. One of the parts is the interaction between scanlines and filtering.

There are two really great figures to help show that interaction:
https://w3c.github.io/PNG-spec/#encoding-png-image
https://w3c.github.io/PNG-spec/#serializing-and-filtering-scanline

Note that these are both in section 4. The section on filter (9) doesn't reference back to these figures:
https://w3c.github.io/PNG-spec/#9Filters

It would be easy to jump to the filtering section miss these figures. Or even if the doc is read top-to-bottom, by the time someone gets to section 9 they may not think to jump back to section 4.

I think one way to improve understanding on filtering is to simply reference these figures from section 9.

**Comment by ProgramMax** [comment]
There is also a sentence "[Figure 15](https://w3c.github.io/PNG-spec/#paethpredictor-function) shows the relative positions of the bytes x, a, b, and c." with the context of filters in general and not specifically the Paeth filter.

Figure 15 does indeed show the positions of those bytes. But it does so in the bottom right corner of the figure. The rest of the figure is specific to Paeth. https://w3c.github.io/PNG-spec/#paethpredictor-function

Perhaps this should be broken into two figures so the general positions of each filter byte are more readily visible.

**Comment by svgeesus** [comment]
> There is also a sentence "[Figure 15](https://w3c.github.io/PNG-spec/#paethpredictor-function) shows the relative positions of the bytes x, a, b, and c." with the context of filters in general and not specifically the Paeth filter.

> Figure 15 does indeed show the positions of those bytes. But it does so in the bottom right corner of the figure. The rest of the figure is specific to Paeth. https://w3c.github.io/PNG-spec/#paethpredictor-function

> Perhaps this should be broken into two figures so the general positions of each filter byte are more readily visible.

Agreed, see https://github.com/w3c/PNG-spec/pull/148

**Comment by svgeesus** [comment]
So given the latest merged commits I think this one can now be closed?

**Comment by ProgramMax** [comment]
I don't think we should close this just yet. I think there are further improvements to be made. I dug a bit deeper and found...


Previously, I had mentioned that the description of filtering is split between sections 4.6.3 and 9.
There is also filtering description in
section 7.3: https://w3c.github.io/PNG-spec/#7Filtering
section 12.7: https://w3c.github.io/PNG-spec/#12Filter-selection
and section 13.8: https://w3c.github.io/PNG-spec/#13Filtering

I believe 13.8 is okay to be independent. It serves more as a reminder. Although, perhaps it should link back to the sections which define the filtering.
The same goes for section 12.7.

I believe section 7.3 and section 4.6.3 both give a general overview. But each one adds/leaves out a bit of information from the other. These two sections should probably be merged into one.

Section 4.6.3 links to section 9, which dives into the details.

Once 7.3 and 4.6.3 are merged, sections 13.8 and 12.7 can link back to the newly merged section. That newly merged section can then link deeper into the details if someone wants more than just an overview.

**Comment by ProgramMax** [comment]
I've reviewed all the changes on this and think we can close it.

It made sense to me that sections 4.6.3 and 7.3 should be merged. But in #174 those sections were reworded in a way that effectively merged them. 4.6.3 introduced the concept of filtering (since it is in the "Concepts" section) and 7.3 elaborates on how it works.

Section 13.8 already links back to the "merged" 7.3. So the only thing that is missing from my old thoughts is a link from 12.7 to 7.3 if someone wants more details. 12.7 gives suggestions and ideas on filter selection. Thinking about it more, I don't think someone would be that deep without already being comfortable with filtering. Further, section 9 (which describes filtering) links to 12.7, which is the correct direction to link.

I'm going to go ahead and close this.
