### ISSUE TITLE
CRC calculation not well defined

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#12]
Raised by: Björn Höhrmann
Originally raised: [04 Mar 2011](https://lists.w3.org/Archives/Public/png-group/2011Mar/0000.html)

> The third issue is the CRC calculation. These days there are very many
things that go by "CRC" with various polynominals and whatnot. Since I'd
rather not code my own implementation, or use the specification's code,
I went looking for the right library, but that's not very easy. It would
have helped if there had been a reference, like saying this is the same
CRC that is used by gzip.

> Similarily, in 5.1 "A four-byte CRC (Cyclic Redundancy Code) calculated
on the preceding bytes in the chunk, including the chunk type field and
chunk data fields, but not including the length field." is confusing.
What is says is that you really only take the type field and the data,
as far as I understand it anyway, so saying "including" the only things
you include is misleading.

**Comment by svgeesus** [comment]
I see that [other people got confused as well](https://stackoverflow.com/questions/24082305/how-is-png-crc-calculated-exactly)

In [Sample Cyclic Redundancy Code implementation](https://w3c.github.io/PNG-spec/#D-CRCAppendix), which is informative, there is sample CRC code which is introduced as follows:

> The following sample code represents a practical implementation of the CRC (Cyclic Redundancy Check) employed in PNG chunks. (See also ISO 3309 [ISO-3309] or ITU-T V.42 [ITU-T-V42] for a formal specification.)

And that [has been there since the very first publication](https://www.w3.org/TR/PNG-CRCAppendix.html) except it originally did not say that it was informative. This looks like an error introduced by PNG 1.2.

So what I think is needed is 

1. to say that the sample code, rather than the entire appendix, is informative.
2. Add a normative reference to the actual CRC algorithm.

It is not the same as the zlib Adler32 checksum. But it does seem to be the same as the [sample CRC from RFC1952](https://datatracker.ietf.org/doc/html/rfc1952#section-8) right down to the comments and the vague reference.

Saying that the CRC is the same as is used in gzip seems useful.

I don't find the "including" language ambiguous, but maybe someone can suggest better wording?

**Comment by ProgramMax** [comment]
In the Aug 8th, 2022 meeting we agreed to link to a normative reference that is clear about CRC polynomials, method, etc. And the sample code should be marked clearly as informative.

@svgeesus is it okay if I assign this to you?
