### ISSUE TITLE
Typos, etc

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#13]
Raised by: Björn Höhrmann
Originally raised: [04 Mar 2011](https://lists.w3.org/Archives/Public/png-group/2011Mar/0000.html)

> (As an aside, the second to last paragraph in 9.2 seems malformed and
there are a couple of " ." instances that should not be there.)

**Comment by ProgramMax** [comment]
I do not see the misplaced "."s.
I do see a comma splice in "Unsigned arithmetic modulo 256 is used, so that...".

I'm adding the "needs resolved discussion" to get more eyes looking for the misplaced "."s.

**Comment by svgeesus** [comment]
There are three occurrences of the string "` .`" in the whole file. All look like simple typos and should be corrected. One is in the **Status of this Document**, one in **4.2 Color Spaces** and one in **11.3.4.2 Keywords and text strings**.
