### ISSUE TITLE
Mention UTF-8 BOM option

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#136]
Existing Latin-1 only locations such as iCCP and tEXt should support a UTF-8 Byte Order Mark.
This should be added.

**Comment by palemieux** [comment]
I am not a big fan of the BOM based on compatibility issues, and recommend we keep it at Latin-1 for this revision.

**Comment by svgeesus** [comment]
Yeah as I said on today's call:

- the most important text-containing chunk, `tEXt` already has a Unicode version, `iTXt`
- the `Profile name` field in `iCCP` is never presented to the user so it is not very important
- ditto the `Palette name` field in `sPLT`, which could be presented to the user but I have never seen it

That is it, currently. So basically we would be adding a pointless testing burden to `tEXt` and `zTXt` for a problem that is already solved with `iTXt`.

**Comment by svgeesus** [comment]
Therefore I recommend we close this issue with no spec change.
