### ISSUE TITLE
Mention current state of filter selection

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#153]
Section 12 mentions what filter selection has worked well in early tests: https://w3c.github.io/PNG-spec/#12Filter-selection
It also mentions "However, it is likely that better heuristics will be found as more experience is gained with PNG".

At this point, I'm sure much more experience has been gained.
We should take inventory of what different PNG encoders do for their filter selection and update this section.

**Comment by svgeesus** [comment]
The optimization program [OptiPNG](https://optipng.sourceforge.net/) has lots of options, but mostly focusing on zlib parameters.  The ones for filter selection are fairly basic. 

From the 

<details><summary>OptiPNG full help</summary>
```
Synopsis:
    optipng [options] files ...
Files:
    Image files of type: PNG, BMP, GIF, PNM or TIFF
Basic options:
    -?, -h, -help       show this help
    -o <level>          optimization level (0-7)                [default: 2]
    -v                  run in verbose mode / show copyright and version info
General options:
    -backup, -keep      keep a backup of the modified files
    -clobber            overwrite existing files
    -fix                enable error recovery
    -force              enforce writing of a new output file
    -preserve           preserve file attributes if possible
    -quiet, -silent     run in quiet mode
    -simulate           run in simulation mode
    -out <file>         write output file to <file>
    -dir <directory>    write output file(s) to <directory>
    -log <file>         log messages to <file>
    --                  stop option switch parsing
Optimization options:
    -f <filters>        PNG delta filters (0-5)                 [default: 0,5]
    -i <type>           PNG interlace type (0-1)
    -zc <levels>        zlib compression levels (1-9)           [default: 9]
    -zm <levels>        zlib memory levels (1-9)                [default: 8]
    -zs <strategies>    zlib compression strategies (0-3)       [default: 0-3]
    -zw <size>          zlib window size (256,512,1k,2k,4k,8k,16k,32k)
    -full               produce a full report on IDAT (might reduce speed)
    -nb                 no bit depth reduction
    -nc                 no color type reduction
    -np                 no palette reduction
    -nx                 no reductions
    -nz                 no IDAT recoding
Editing options:
    -snip               cut one image out of multi-image or animation files
    -strip <objects>    strip metadata objects (e.g. "all")
Optimization levels:
    -o0         <=>     -o1 -nx -nz                             (0 or 1 trials)
    -o1         <=>     -zc9 -zm8 -zs0 -f0                      (1 trial)
                (or...) -zc9 -zm8 -zs1 -f5                      (1 trial)
    -o2         <=>     -zc9 -zm8 -zs0-3 -f0,5                  (8 trials)
    -o3         <=>     -zc9 -zm8-9 -zs0-3 -f0,5                (16 trials)
    -o4         <=>     -zc9 -zm8 -zs0-3 -f0-5                  (24 trials)
    -o5         <=>     -zc9 -zm8-9 -zs0-3 -f0-5                (48 trials)
    -o6         <=>     -zc1-9 -zm8 -zs0-3 -f0-5                (120 trials)
    -o7         <=>     -zc1-9 -zm8-9 -zs0-3 -f0-5              (240 trials)
    -o7 -zm1-9  <=>     -zc1-9 -zm1-9 -zs0-3 -f0-5              (1080 trials)
Notes:
    The combination for -o1 is chosen heuristically.
    Exhaustive combinations such as "-o7 -zm1-9" are not generally recommended.
Examples:
    optipng file.png                                            (default speed)
    optipng -o5 file.png                                        (slow)
    optipng -o7 file.png                                        (very slow)
```
</details>

```
Optimization levels:
    -o0         <=>     -o1 -nx -nz                             (0 or 1 trials)
    -o1         <=>     -zc9 -zm8 -zs0 -f0                      (1 trial)
                (or...) -zc9 -zm8 -zs1 -f5                      (1 trial)
    -o2         <=>     -zc9 -zm8 -zs0-3 -f0,5                  (8 trials)
    -o3         <=>     -zc9 -zm8-9 -zs0-3 -f0,5                (16 trials)
    -o4         <=>     -zc9 -zm8 -zs0-3 -f0-5                  (24 trials)
    -o5         <=>     -zc9 -zm8-9 -zs0-3 -f0-5                (48 trials)
    -o6         <=>     -zc1-9 -zm8 -zs0-3 -f0-5                (120 trials)
    -o7         <=>     -zc1-9 -zm8-9 -zs0-3 -f0-5              (240 trials)
    -o7 -zm1-9  <=>     -zc1-9 -zm1-9 -zs0-3 -f0-5              (1080 trials)
```

so o1 to o3 choose between no filter (0) and Paeth (5) while o4 onward try all filers for each scanline.

From the [documentation for OptiPNG](https://optipng.sourceforge.net/pngtech/optipng.html):

> It was experimentally observed that the LZ77 search is occasionally capable of producing smaller PNGs if it is less exhaustive. The reason behind this act resides in the same category of "strategic searches" discussed here. Unfortunately, there is no known method of anticipating which search level (from the fastest and the least exhaustive, to the slowest and the most exhaustive) is better, other than assuming "the most exhaustive is better in most cases". 

Here are [some examples where no filtering is best](https://optipng.sourceforge.net/pngtech/better-filtering.html)

The older [pngcrush](https://pmt.sourceforge.io/pngcrush/) has a _brute_  option which exhaustively tries everything and keeps the smallest file.

I'm not seeing any documented better heuristics.

**Comment by svgeesus** [comment]
[@DavidBuchanan314](https://github.com/DavidBuchanan314) previously [said](https://github.com/w3c/PNG-spec/issues/256#issue-1536576236)

> Perhaps it should be explicitly stated that more advanced heuristics (and meta-heuristics, and brute-force techniques) are known to exist (depending on scenario).

Such as?

**Comment by svgeesus** [comment]
From [the PNG Book](http://www.libpng.org/pub/png/book/chapter09.html) (second edition 2002-2003, so not super recent) mentions _possible future_ heuristics:

> A related heuristic--still experimental at the time of this writing--is to use the weighted sum of absolute differences. The theory, to some extent based on empirical evidence, is that switching filters too often can have a deleterious effect on the main compression engine. A better approach might be to favor the most recently used filter even if its absolute sum of differences is slightly larger than that of other filters, in order to produce a more homogeneous data stream for the compressor--in effect, to allow short-term losses in return for long-term gains. The standard PNG library contains code to enable this heuristic, but a considerable amount of experimentation is yet to be done to determine the best combination of weighting factors, compression levels, and image types.

> One can also imagine heuristics involving higher-order distance metrics (e.g., root-mean-square sums), sliding averages, and other statistical methods, but to date there has been little research in this area. Lossless compression is a necessity for many applications, but cutting-edge research in image compression tends to focus almost exclusively on lossy methods, since the payoff there is so much greater. Even within the lossless domain, preconditioning the data stream is likely to have less effect than changing the back-end compression algorithm itself. So let's take a look at that next.

**Comment by svgeesus** [comment]
The readme for [pngwolf-zopfli](https://github.com/jibsen/pngwolf-zopfli#pngwolf-zopfli) says:

> pngwolf employs a genetic algorithm to find better filter combinations than traditional heuristics. It derives a couple of filter combinations heuristically, adds a couple of random combinations, and then looks how well each combination compresses. Two very different combinations may compress similarily well, for instance, one combination may be very good for the first couple of scanlines, while the other may be very good for the last couple of scanlines. So taking the beginning of one combination and the tail of the other to make a new one may result in a combination that compresses better then the original two.

**Comment by svgeesus** [comment]
We should not assume that smallest possible PNG size is the goal regardless of encode time or decode time. From [the filtering section of the PyPNG docs](https://pypng.readthedocs.io/en/main/tr20091230.html#filtering):

> In a test, a 4 megapixel RGB test image with no filtering (filter type 0 for each scanline) decoded in about 3.5 seconds. The same image recoded to use a Paeth filter for each scanline (using Netpbm’s pnmtopng -paeth) decodes in about 32 seconds: 9 times slower!

> If you have any choice in the matter, and you want PyPNG to go quickly, do not filter your PNG images when saving them. PyPNG does not filter its images when saving them, and offers no options to enable filtering.

**Comment by svgeesus** [comment]
The [libpng source code, lines 2415-2443](https://github.com/kikinteractive/libpng/blob/b07750220ef71cb4e943560ef0e60430fe3e63a5/pngwutil.c#L2415-L2443):

> 
   /* The prediction method we use is to find which method provides the
    * smallest value when summing the absolute values of the distances
    * from zero, using anything >= 128 as negative numbers.  This is known
    * as the "minimum sum of absolute differences" heuristic.  Other
    * heuristics are the "weighted minimum sum of absolute differences"
    * (experimental and can in theory improve compression), and the "zlib
    * predictive" method (not implemented yet), which does test compressions
    * of lines using different filter methods, and then chooses the
    * (series of) filter(s) that give minimum compressed data size (VERY
    * computationally expensive).
    *
    * GRR 980525:  consider also
    *
    *   (1) minimum sum of absolute differences from running average (i.e.,
    *       keep running sum of non-absolute differences & count of bytes)
    *       [track dispersion, too?  restart average if dispersion too large?]
    *
    *  (1b) minimum sum of absolute differences from sliding average, probably
    *       with window size <= deflate window (usually 32K)
    *
    *   (2) minimum sum of squared differences from zero or running average
    *       (i.e., ~ root-mean-square approach)
    */


   /* We don't need to test the 'no filter' case if this is the only filter
    * that has been chosen, as it doesn't actually do anything to the data.
    */

**Comment by ProgramMax** [comment]
I suspect filter selection methods will change in the future, too.

For example, if the 4th Edition focuses on restart markers and allowing parallel decoding, a scan line starting at a restart marker shouldn't use a filter which references previous scan lines. If it does, the whole point of the restart marker is undone.

And in far future editions, we might want to consider more GPU-friendly approaches that push the parallelization even further. An appropriate filter function in that scenario shouldn't reference the previous pixel in a scan line because then the entire scan line becomes serial. Maybe it could operate on something like macro blocks and reference values within its block. (This is far future because a scan line would be serial anyway due to the deflate stream restart markers. For this option to work, deflate might not be the best option.)

If we don't have a clear best current method and the best future method will change, should we simply not suggest how filter selection should work?

**Comment by svgeesus** [comment]
So, would we delete just this part:

> The following simple heuristic has performed well in early tests: compute the output scanline using all five filters, and select the filter that gives the smallest sum of absolute values of outputs. (Consider the output bytes as signed differences for this test.) This method usually outperforms any single fixed filter type choice. However, it is likely that better heuristics will be found as more experience is gained with PNG.

or would we delete the entire [12.7 Filter selection]()https://w3c.github.io/PNG-spec/#12Filter-selection?

**Comment by ProgramMax** [comment]
If the general guidance of 12.7 is still correct-enough, I would keep it. But I would change the wording to something like "Each unique image will have a different set of filters which perform best for it. An encoder could try every combination of filters to find what works best for a given image. However, if an exhaustive search is unacceptable, here are some general heuristics which may perform well enough: ..."
