### ISSUE TITLE
Several [[#blah]]s are broken

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#173]
I just noticed several ReSpec links of the form [[#blah]] are broken.

Investigate and fix these.

**Comment by svgeesus** [comment]
[automatic link check of the PNG ED](https://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2FPNG-spec%2F&hide_type=all&depth=&check=Check)

Broken fragments:

    https://w3c.github.io/PNG-spec/#iend-image-trailer (lines 1731, 2021, 2313, 3355, 3357, 6444, 6465, 6479, 7759, 7764, 7844, 7849)
    https://w3c.github.io/PNG-spec/#chrm-primary-chromaticities-and-white-point (lines 1742, 2337, 2713, 3952, 3960, 4167, 4187, 4236, 4242, 4245, 5821, 5825, 5854, 5863, 5869, 5873, 5877, 5880, 7172, 7177, 7202, 7213, 7218, 7223, 7225)
    https://w3c.github.io/PNG-spec/#gama-image-gamma (lines 1743, 2351, 2707, 2712, 2721, 3951, 3959, 3965, 4165, 4177, 4235, 4241, 4244, 5626, 5635, 5642, 5665, 5693, 5708, 5716, 5727, 5736, 5765, 5788, 5792, 5823, 5826, 5855, 6404, 6471, 6487, 7079, 7096, 7115, 7201, 8383)
    https://w3c.github.io/PNG-spec/#actl-animation-control (line 1767)
    https://w3c.github.io/PNG-spec/#hist-image-histogram (lines 1756, 2394, 6152, 6171, 6220, 7565)
    https://w3c.github.io/PNG-spec/#11fdAT (line 2436)
    https://w3c.github.io/PNG-spec/#chrm-primary-chromaticitieis-and-white-point (line 3966)
    https://w3c.github.io/PNG-spec/#splt-suggested-palette (lines 1758, 2429, 3561, 3564, 6116, 6125, 6137, 6181, 6187, 6197, 6202, 6207, 6213, 6217, 6222, 6632, 7512, 7559, 7564)
    https://w3c.github.io/PNG-spec/#fctl-frame-control (line 1768)
    https://w3c.github.io/PNG-spec/#4Concepts.APNGSequence (line 1821)
    https://w3c.github.io/PNG-spec/#itxt-international-textual-data (lines 1750, 2448, 3317, 4372, 4496, 4500, 4555, 6306, 6532, 6626, 6752, 7708, 8285)
    https://w3c.github.io/PNG-spec/#bkgd-background-colour (lines 1755, 2386, 5996, 5998, 6143, 6156, 6165, 6195, 7237, 7240, 7242, 7251, 7253, 7257, 7269, 7543, 7546)
    https://w3c.github.io/PNG-spec/#iccp-embedded-icc-profile (lines 1744, 2358, 2362, 2380, 2709, 2715, 3318, 3766, 3836, 3867, 3890, 4249, 5621, 5628, 5812, 6533, 6630, 7117)
    https://w3c.github.io/PNG-spec/#sbit-significant-bits (lines 1745, 2368, 3991, 6078, 6081, 6102, 6104, 6997, 6999, 7007, 7011, 7013)
    https://w3c.github.io/PNG-spec/#srgb-standard-rgb-colour-space (lines 1746, 2363, 2375, 2379, 2708, 2714, 3767, 3835, 3866)
    https://w3c.github.io/PNG-spec/#trns-transparency (lines 1739, 2402, 2742, 2747, 2751, 4080, 5991, 6174, 6470, 6489, 7016, 7260, 7262, 7270, 7486, 7488, 7529, 7533, 7949)
    https://w3c.github.io/PNG-spec/#fdat-frame-data (line 1769)
    https://w3c.github.io/PNG-spec/#exif (line 1759)
    https://w3c.github.io/PNG-spec/#animation-information (lines 1806, 1826)
    https://w3c.github.io/PNG-spec/#ztxt-compressed-textual-data (lines 1752, 2460, 3320, 4373, 4491, 4494, 6302, 6531, 6627, 6754, 6760, 6769, 7707, 8281)
    https://w3c.github.io/PNG-spec/#time-image-last-modification-time (lines 1763, 2155, 2442, 7705)
    https://w3c.github.io/PNG-spec/#cicp-video-rendering-colour-spaces (line 1747)
    https://w3c.github.io/PNG-spec/#11fcTL (line 2416)
