### ISSUE TITLE
Which location (or background) was used for a photo

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#18]
Raised by: Bill
Originally raised: [21 Mar 2017](https://lists.w3.org/Archives/Public/png-group/2017Mar/0000.html)

> I was not successful clicking on the PNG-EXTENSIONS link.  It was 
supposed to provide "PNG 1.2 Specification, Version 1.2.0".

> What I need is the ability to store the location of the camera so that I 
know which of several background images was used.  I already know the 
day the image was taken, but, I need to know which background was used 
that day for that camera for that picture.  In my case the background on 
any particular day is the same for the location.  As an alternative I 
could store the name of the background image - I would simply include 
the location name in the background image name.

**Comment by svgeesus** [comment]
The problem does not seem to be well specified, and not easily generalizable. A text field such as `Comment` seems adequately flexible for this task.

**Comment by ProgramMax** [comment]
Agreed. My understanding of the "background" is just another way to say location.
The first sentence says they need to store the location of the camera.

Luckily, the proposed eXIf chunk from #28 would solve that.

I'm closing this as a duplicate.
