### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#190]
All links must be working in order to publish a First Public Working Draft.
https://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2FPNG-spec%2F&hide_type=all&depth=&check=Check

Fix any broken links.

**Comment by ProgramMax** [comment]
Good news and bad:

- There was a broken link. I have fixed it and will open a pull request. But before I do...
- The tool also complains about ReSpec-generated fragments.

This makes sense and is worth a discussion.

Elsewhere in the spec, we have links like `<a>foo</a>`. These have no href attribute. The W3C Link Checker does not complain about them.
For these to work, the "foo" text needs to be the name of the thing it is linking to. This works well for things like definitions, where you can have `<a>pixel</a>`.

However, it is a bit more difficult when the section name either

- is a description (rather than a word), such as "acTL Animation Control Chunk", or more generally
- does not flow in a sentence, such as "...an acTL chunk must appear..." vs. "...an actl Animation Control Chunk must appear..."

Links of the form `<a href="#actl-animation-control-chunk">acTL</a>` are how we overcame these difficulties. But since the page does not contain that fragment until JavaScript runs, the W3C Link Checker does not see them.

I think our best solution is for us to specify our own fragment identifiers and not use ReSpec generated ones.

Previously, I wanted us to rely on ReSpec-generated fragment identifiers. If I knew then what I know now, I wouldn't have. This also made me realize that a user who has disabled JavaScript would also not be able to use ReSpec-generated fragment identifiers. For this reason, I'm also no longer sure about `<a>foo</a>` style links. I think we might want to provide hard-coded fragments for those, too.

For now, I will only add hard-coded fragments needed to satisfy the W3C Link Checker. But we should discuss potentially also hard-coding each definition.

**Comment by palemieux** [comment]
> I think our best solution is for us to specify our own fragment identifiers and not use ReSpec generated ones.

Yes.

**Comment by ProgramMax** [comment]
In that case, we should be checking against the exported version.

I could perhaps create a GitHub action which triggers on pull request, updating the pull request with the exported page.
Generally, I do not like this approach. I don't want GitHub actions to be able to commit.

I could also make a GitHub action that requires (and reminds people) to include the exported page in their pull request.
This is a pain in the butt. But it is actually similar to how a lot of style guide enforcement works. In fact, if we ever do some automated formatting, that is what I planned on doing.

As much as I want style / formatting enforcement (and perhaps also export enforcement), it adds hurdles to committing. Right now, I think we should instead remove hurdles. So neither of these GitHub actions seem great.

I think I'll just manually confirm that the exported page passes W3C's Link Checker.

**Comment by svgeesus** [comment]
> it adds hurdles to committing. Right now, I think we should instead remove hurdles.

Strongly agree.

**Comment by ProgramMax** [comment]
Although broken links are now fixed, I should point out that W3C's Link Checker still complains because one link has a URI scheme it doesn't check, "mailto:".

If the goal is to satisfy the Link Checker with no exceptions, we'll need to address that.
But if human oversight is allowed, I don't think we need to worry.
