### ISSUE TITLE
Internal link style is inconsistent

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#194]
ReSpec has two styles of internal link styling:
`<a href="#foo">Foo</a>`, and
`<a href="#foo"></a>`

The first will do exactly as expected. The second populates the anchor with the full section number and title.

Through out the spec, we sometimes use the first style and sometimes use the second style. There might be good times to use one or the other. So we might not want a string rule such as "everything must be the second style". But we should probably have some thought and rules in place.

While we're at it, sometimes this is mixed. For example, [the zTXt chunk definition](https://w3c.github.io/PNG-spec/#11zTXt) currently has "`...same as the <a href="#11tEXt">tEXt</a> chunk (see <a href="#11tEXt"></a>).`" Having two links go to the same place is already silly. But using two different styles is even more strange.

**Comment by ProgramMax** [comment]
I should mention, those two styles and up appearing as:
"...same as in the [tEXt](https://w3c.github.io/PNG-spec/#11tEXt) chunk (see [11.3.3.2 tEXt Textual data](https://w3c.github.io/PNG-spec/#11tEXt))."

**Comment by palemieux** [comment]
> Having two links go to the same place is already silly. But using two different styles is even more strange.

I suggest removing the redundant `see <a href="#11tEXt"></a>`.

> ReSpec has two styles of internal link styling:

*`<a href="#foo"></a>` for sections/clauses
*`<a href="#tEXt">tEXt</a>` for chunks?

**Comment by ProgramMax** [comment]
Agreed on removing the redundant one in this example.

Style-wise, I think if either
1.) the sentence flow would be interrupted, or
2.) short text is a goal
 we should not let ReSpec complete the link text.
 I'm trying to think of other cases. Using ReSpec completion for all other cases might be extreme.
 
 Examples of these two idea are "...the same as the tEXt chunk." It would be weird to read "...the same as the 11.3.3.2 tEXt Textual data chunk."
 
 Also, at [Chunk ordering](https://w3c.github.io/PNG-spec/#5ChunkOrdering) there is a table with the chunk names in a column. I don't think that should be expanded out. Nor the ordering constraints column.
 
 Text like "...see 11.3.3.2 tEXt Textual data" don't seem to interrupt the flow of the sentence. So that seems appropriate to me.
 
 Thoughts?

**Comment by svgeesus** [comment]
Agreed, go for the shorter link text in general, and where it makes sense use the longer, section references.
