### ISSUE TITLE
Are unsigned integers of the hIST chunk PNG two-byte unsigned integers?

### ISSUE THREAD

**Issue by palemieux** [w3c/PNG-spec#216]
The `hIST` chunk specifies:

_The hIST chunk contains a series of two-byte (16-bit) unsigned integers_

Are these unsigned integers PNG two-byte unsigned integers?

**Comment by randy408** [comment]
It does say that.

**Comment by palemieux** [comment]
@randy408 Where does it state that?

**Comment by randy408** [comment]
https://www.w3.org/TR/2003/REC-PNG-20031110/#11hIST

> The hIST chunk contains a series of two-byte (16-bit) unsigned integers

And they're big-endian like every other >8-bit integer.

**Comment by palemieux** [comment]
@randy408 Sure, but are they limited to the range 0 to 2^16-1, which is what would make them *PNG* two-byte unsigned integers. See terms and definition section.

**Comment by randy408** [comment]
> See terms and definition section.

I don't see an entry for it, only for _four-byte_ integers. If you're thinking it's limited to `(2^15)-1 = 32767` that is not the case. Unlike four-byte unsigned integers that are limited to `2^31-1`, two-byte integers can express the full range of values (`0-65535`).

**Comment by palemieux** [comment]
> If you're thinking it's limited to (2^15)-1 = 32767 that is not the case.

Thanks

> I don't see an entry for it

https://w3c.github.io/PNG-spec/#dfn-png-two-byte-unsigned-integer

**Comment by randy408** [comment]
Ah right, the new draft has it:

* PNG four-byte unsigned integer

>a four-byte unsigned integer limited to the range 0 to 2^31-1.
>Note
>    The restriction is imposed in order to accommodate languages that have difficulty with unsigned four-byte values.
* PNG two-byte unsigned integer
>    a two-byte unsigned integer limited to the range 0 to 2^16-1.
>    Note
    The restriction is imposed in order to accommodate languages that have difficulty with unsigned two-byte values.

I believe the note for the latter doesn't belong there.

**Comment by palemieux** [comment]
> I believe the note for the latter doesn't belong there, nor the term "limited".

See `delay_num` and `delay_den` at `fcTL`
