### ISSUE TITLE
Are PNG four-byte signed integer used anywhere in the specification?

### ISSUE THREAD

**Issue by palemieux** [w3c/PNG-spec#217]
I could not find any evidence.

**Comment by randy408** [comment]
In the Image Offset (oFFs) chunk and maybe other extensions.

**Comment by ProgramMax** [comment]
Oh geeze. I didn't even think about the extensions doc. That has been so far out of my mind...

Should the [spec itself](https://w3c.github.io/PNG-spec) contain definitions only used in the [extensions doc](https://w3c.github.io/PNG-spec/extensions/Overview.html)?

(And separately, do we need to look over the extensions doc to make sure it is ready?)

**Comment by ProgramMax** [comment]
I was more vague than I meant with that last question.
Yes, we need to make sure it is ready. But I haven't reviewed it to make sure it is. So I'll look into that.

**Comment by palemieux** [comment]
>Should the spec itself contain definitions only used in the extensions doc?

No IMHO

**Comment by palemieux** [comment]
@randy408 @ProgramMax See https://github.com/w3c/PNG-spec/pull/222
