### ISSUE TITLE
Call for Consensus: publish First Public Working Draft

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#219]
This GitHub issue is to establish consensus on publishing a First Public Working Draft. W3C Working Group participants should reply with affirmation, dissent, or may abstain.

**Should we publish a First Public Working Draft?**

#### Major changes in FPWD addressed

All of our core goals have been obtained. These are:

- the new cICP chunk defined
- the new APNG chunks defined
- the iCCP chunk versioning issues addressed

In addition, other important changes have been resolved such as including XMP and EXIF in the core spec.
I believe all technical wording is now stable, as required to publish a First Public Working Draft.
There are still minor, non-technical changes which may be made after FPWD such as typographical changes or fixing validator errors and warnings.

#### Process

[Consensus is a core value to the W3C.](https://www.w3.org/2021/Process-20211102/#Consensus) I have assigned this issue to all [PNG WG participants who have their GitHub profile listed](https://www.w3.org/groups/wg/png/participants). I was unable to include Simon Thompson. I will send them an email with a link to this issue and direct them to respond to the public mailing list if they choose.

A WG participant may register a [Formal Objection](https://www.w3.org/2021/Process-20211102/#FormalObjection) if they would like Director consideration.

WG participants may respond with a simple yes/no or similar. They may also elaborate. If dissenting, elaboration is encouraged in order to identify issues and find solutions. The [W3C process on managing dissent](https://www.w3.org/2021/Process-20211102/#managing-dissent) states that we will try to address concerns as much as is reasonable and should move on once that is done.

#### Call to action

Working group participants should reply with their stance on publishing a First Public Working Draft.

**Comment by lrosenthol** [comment]
Yes

I support moving to FPWD.  As noted, we still have some editorial work to do, but I believe that all of the technical items we had identified for this release are done.

**Comment by svgeesus** [comment]
Yes

**Comment by digitaltvguy** [comment]
Yes, I approve with subtle changes to nomenclature just submitted for review.

• Changed to "CICP image format signaling metadata"
• Changed generic descriptions of "colour space" to Colour Space, Transfer Function and Matrix Coefficients. (more informative of function)
• Added "Wide Colour Gamut" to description of CICP signaling capabilities.

**Comment by chrisn** [comment]
I support publication as FPWD. Thank you for all the work you've done!

BTW, Simon Thompson is @simontWork

**Comment by ProgramMax** [comment]
Thank you, Chris Needham. For some reason, I am unable to add them to the assignees list. I'll look into it.

**Comment by chrisn** [comment]
It may be because he hasn't associated his GitHub account with his W3C account.

**Comment by simontWork** [comment]
Agreed.

Would it be possible to expand on narrow-range and full-range?  It's a bit of a minefield of nomenclature clashes.  EBU have tried to explain why full-range changes based on context: https://tech.ebu.ch/docs/r/r103.pdf

**Comment by digitaltvguy** [comment]
> Agreed.
> 
> Would it be possible to expand on narrow-range and full-range? It's a bit of a minefield of nomenclature clashes. EBU have tried to explain why full-range changes based on context: https://tech.ebu.ch/docs/r/r103.pdf

Hi Simon,

I added some detail and created a pull request.

-Chris

**Comment by ProgramMax** [comment]
Yes.

@palemieux, you are not required to vote. But if you want to, you are the final voice to be heard.

**Comment by palemieux** [comment]
@ProgramMax I suggest that the three remaining broken definitions (`truecolour`, `zlib` and `CRC` ) be fixed before FPWD. We should be able to do so before Monday me thinks.

**Comment by palemieux** [comment]
> WG participants may respond with a simple yes/no or similar. 

Yes.

**Comment by ProgramMax** [comment]
Thank you, everyone. We have unanimous consent. I'm marking this issue as closed.

**Comment by svgeesus** [comment]
**How it started:**
![image](https://user-images.githubusercontent.com/2506926/196245998-8bcbefb4-4521-4948-b827-0567b5f224af.png)

**How it's going:**
![image](https://user-images.githubusercontent.com/2506926/196246172-4a365f53-f793-4dba-b748-d3310847941e.png)
