### ISSUE TITLE
PNG restricts ICC to ICC v.2

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#22]
Raised by: Phil Green

> A profile is embedded in a PNG file as a chunk with type ‘iCCP’, identifying an arbitrary profile name, compression method, and the compressed profile. Alternatively, a PNG file can implicitly reference an sRGB transform in an ‘sRGB’ chunk type. Full details are given in the PNG specification at https://www.w3.org/TR/PNG/. Currently the PNG specification restricts the ICC profile to v2.

The latest versions of ICC are :

Specification ICC.1:2010-12 (Profile version 4.3.0.0) Image technology colour management - Architecture, profile format, and data structure 
http://www.color.org/icc_specs2.xalter which is also published as ISO 15076-1, 

and 

Specification ICC.2:2019 (iccMAX) Image technology colour management - Extensions to architecture, profile format, and data structure 
http://www.color.org/icc_specs2.xalter which is also published as ISO 20677-1

**Comment by svgeesus** [comment]
The restriction to v.2 was not intentional, it was simply the latest version available at the time that PNG second edition was standardized.

In practice, ICC v.4 profiles are routinely embedded in PNG images.

The specification should be updated to point to the latest ICC specifications.

**Comment by svgeesus** [comment]
The normative references are now:

> ICC-1, International Color Consortium, "Specification ICC.1:2010-12 (Profile version 4.3.0.0) Image technology colour management - Architecture, profile format, and data structure, available at http://www.color.org/icc_specs2.xalter also published as ISO 15076-1

> ICC-2, International Color Consortium, "Specification ICC.2:2019 (iccMAX) Image technology colour management - Extensions to architecture, profile format, and data structure, available at http://www.color.org/icc_specs2.xalter also published as ISO 20677-1

**Comment by svgeesus** [comment]
I alerted Phil Green (ICC Technical Secretary) to this change, and await his confirmation that this solves the issue.

**Comment by svgeesus** [comment]
> Hi Chris

> Fantastic, thanks. Good to see iccMAX supported as well as v4. I'll update the profile embedding document.

> Phil

**Comment by AlexTMjugador** [comment]
The current first public working draft of the third edition of the spec does not mention ICC v2 as a normative reference, which means that iCCP chunks with ICC v2 profile data do no longer conform to the spec.

Is this an unintentional side effect of scrapping the iCCN chunk? Also, the normative ICC-2 reference is cited on the sRGB chunk, but not for iCCP. Moving forward, how should the PNG specification handle future major revisions of the ICC standard?
