### ISSUE TITLE
Definition of two-byte unsigned integer is redundant and confusing

### ISSUE THREAD

**Issue by randy408** [w3c/PNG-spec#221]
As demonstrated by #216. Two-byte unsigned integers always expressed the full range of possible values, `0` to `(2^16)-1` ie `0-65535`, not `0` to `(2^15)-1` or `0-32767`, any mention of "limited" is redundant and confusing as it's immediately preceded by the four-byte unsigned integer definition, which is limited to a range of values and uses similar wording. There is no mention in the previous specification of two-byte unsigned integers being anything other than the full range of possible values, the `sPLT` chunk explicitly specifies a range of "0 to 65535" for sample depths of 16.

https://w3c.github.io/PNG-spec/#dfn-png-two-byte-unsigned-integer

>**_PNG two-byte unsigned integer_**
>    a two-byte unsigned integer limited to the range 0 to 2^16-1.
>NOTE
>    The restriction is imposed in order to accommodate languages that have difficulty with unsigned two-byte values.

The note and everything after and including "limited" doesn't belong there.

**Comment by palemieux** [comment]
I propose to simply remove the definition.

**Comment by palemieux** [comment]
@randy408 See https://github.com/w3c/PNG-spec/pull/223
