### ISSUE TITLE
Adding support for HDR imagery to the PNG format

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#23]
There is a requirements document [Adding support for HDR imagery to the PNG format](https://github.com/w3c/ColorWeb-CG/blob/master/png_cicp_chunk_proposal.md) to add HDR colorspace signalling to PNG. It is based on the H.273 controlled vocabulary.

The `cICP` chunk could be seen as like the `sRGB` chunk (signal colorspace with very few bytes, much less than an ICC profile) except it covers the common formats needed for HDR, several of which cannot be expressed with just chromaticities and a simple gamma exponent.

see also https://github.com/w3c/ColorWeb-CG/issues/11

**Comment by randy408** [comment]
> https://github.com/w3c/ColorWeb-CG/blob/master/png_cicp_chunk_proposal.md

Link is dead.

**Comment by svgeesus** [comment]
https://github.com/w3c/ColorWeb-CG/blob/master/hdr-in-png-requirements.md

**Comment by svgeesus** [comment]
The earlier work [Using the ITU BT.2100 PQ EOTF with the PNG Format](https://www.w3.org/TR/png-hdr-pq/) relied on the **name** of the ICC profile as a signalling mechanism. Actually applying that ICC profile gave poor results, as Dmitry Kazakov (Krita) explained in [his talk at the Coor Workshop](https://www.w3.org/Graphics/Color/Workshop/slides/talk/kazakov):

![tt-pq-rendering](https://user-images.githubusercontent.com/2506926/130611070-bfe73ede-1329-43ba-9098-2fb48bda98d8.png)

**Comment by digitaltvguy** [comment]
### For PNG Specification Addition: 11.3.3.5 Coding-independent code points for video signal type identification (For cICP chunk)

### REFERENCES ITU-T H.273 7/2021

H.273 Section 8.1 – Table 2 – Colour Primaries
Type Unsigned Integer, enumeration
Range 0-255;
ColourPrimaries indicates the chromaticity coordinates of the source colour primaries as specified in Table 2 in terms of the CIE 1931 definition of x and y as specified by ISO 11664-1

H.273 Section 8.2 – Table 3 – Transfer Function
Type Unsigned Integer, enumeration
Range 0-255;
Transfer Function indicates the reference opto-electronic transfer characteristic function (OETF) of the source picture as a function

H.273 Section 8.3 - FullRangeFlag
Type Unsigned Integer, enumeration
FullRangeFlag (1=FullRange and is default for RGB Images)
Specifies the scaling factor within the quantized digital signal

**Comment by digitaltvguy** [comment]
> > https://github.com/w3c/ColorWeb-CG/blob/master/png_cicp_chunk_proposal.md
> 
> Link is dead.

https://github.com/w3c/ColorWeb-CG/blob/master/hdr-in-png-requirements.md

**Comment by svgeesus** [comment]
[cICP is now in the Editor's Draft](https://w3c.github.io/PNG-spec/#11cICP)

**Comment by ProgramMax** [comment]
I'm adding a 2nd "needs" tag since this issue blurs the line between a meta-issue and an individual issue (for cICP).

Issue #95 is a child issue of this meta-issue.
