### ISSUE TITLE
Add ST 2086 metadata chunk

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#236]
cICP + leaving it up to the system is not enough to properly display HDR content.
For example, Chrome currently uses HDR mastering metadata to (I believe) scale HDR content to match max luminance on a SDR display. Others might (probably) use this information differently.

This means for example two identical images next to each other might look different if only one is scaled. Or an HDR image + HDR canvas.

For PNG to remain consistent with other content, PNG will need to include HDR mastering metadata.

I believe a new chunk for ST 2086 would be useful for this purpose. It should not be present if the image isn't HDR.

**Comment by palemieux** [comment]
In addition to SMPTE ST 2086 metadata, MaxFALL and MaxCLL, which are routinely carried with HDR video, should also be supported.

See Annex B of [1] as an example:

https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9097487

**Comment by svgeesus** [comment]
So [SMPTE ST 2086 costs $80](https://ieeexplore.ieee.org/document/8353899). Can we word this chunk such that developers can implement without needing to purchase it? While still citing SMPTE ST 2086 as the normative reference.

**Comment by palemieux** [comment]
> So [SMPTE ST 2086 costs $80](https://ieeexplore.ieee.org/document/8353899). Can we word this chunk such that developers can implement without needing to purchase it? While still citing SMPTE ST 2086 as the normative reference.

Copy the syntax from the reference (ST 2067-21) cited above. The syntax is complete and the reference is available for free.

**Comment by svgeesus** [comment]
Also is this a simple enumeration (there are basically three values, corresponding to 709/sRGB, BT.2020/2100, and P3D65) or do the values need to be in there as chunk data, eg the primary and white point chromaticities?

If the latter should the chromaticities be encoded as ST 2086 does (multiply by 0.000,02 to get the float value) , e.g. for 2020

> { 35400, 14600 } { 8500, 39850 } { 6550, 2300 }

or [as the cHRM chunk](https://www.w3.org/TR/png/#11cHRM) does, (multiply by 0.000,001 to get the float value) e.g.

> [ 708000, 292000] [170000, 797000] [131000, 46000 ]

**Comment by palemieux** [comment]
> Also is this a simple enumeration 

No. These are continuous values.

> If the latter should the chromaticities be encoded as ST 2086 does (multiply by 0.000,02 to get the float value) , e.g. for 2020

I would use the encoding from ST 2067-21, which also that used in Rec. ITU-T H.265:

![image](https://user-images.githubusercontent.com/4871350/201121918-04462bc4-1243-4a9f-a5bc-52cbe68d867b.png)

This allows the values to be simply copied when grabbing a frame.

**Comment by svgeesus** [comment]
Since MaxFALL and MaxCLL are computed on content and are absolute luminance in nits (cd/m^2), does that mean they are only applicable to PQ content and not HLG?

**Comment by svgeesus** [comment]
Answering my own question they are not used for BT2100 PQ (or HLG) but are used for HDR10 (which uses PQ)

**Comment by ProgramMax** [comment]
I am repurposing this issue to be about the new ST 2086 metadata chunk.

ST 2086 metadata includes:

- Mastering display primaries
- Mastering display white point
- Mastering display maximum luminance
- Mastering display minimum luminance

The primaries are 3 * 4 bytes. Each 4 bytes specifies a 16-bit x and 16-bit y in units of 0.00002. For example, (0.6800, 0.3200) is stores as {34000,16000}.

The white point is similar, 4 bytes.

The max and min luminance are 4 bytes in units of 0.0001 cd/m^2.

Some things we should resolve before editing the spec are:

- What is a good 4 character name for this chunk?
- How much do we want to specify?

Since all of the values in this chunk revolve around the display used when mastering, perhaps a good name would invoke that?

During our Nov 14th meeting, we discussed that it isn't clear how much we should specify. It was suggested that we look at ITU docs and see how they reference ST 2086. The trick here is sometimes people fudged the max/min luminance to get the look they want, ignoring what their actual monitor supported. This was of course dependent on the algorithm being used by their viewer. And if we wanted to be very specific, is the max the sustained full screen max luminance, or just a small area?

**Comment by ProgramMax** [comment]
I forgot to mention: This new chunk's placement should be before the IDAT.

**Comment by ProgramMax** [comment]
During our last meeting, I said I would make a very rough first pass at this just to get the ball rolling.
But then I realized maybe @palemieux would want to? BUT then I realize I also just assigned two iTXt issues to @palemieux so maybe I should to it to distribute the load.
I think I'll go ahead and do it. BUT...I'm not sure what to name it. "2086" would be nice, but it has to be letters, not numbers.

I might just go with a name like "temp" until we think of a better one.

**Comment by svgeesus** [comment]
This is about mastering metadata. It is ancillary and safe-to-copy so the first and last letters are lower case. So I propose `mASt` (short for mastering)

**Comment by digitaltvguy** [comment]
> Answering my own question they are not used for BT2100 PQ (or HLG) but are used for HDR10 (which uses PQ)

In my opinion ST 2086 should be allowed for SDR, PQ10, or HLG.  There are examples in ST 2067:21 for SDR, ITU-T Series H Supplement 19 and efforts in ISO for it's use in HLG.  For SDR it would identify MDCV of 100/203nits which differ in some "single-master" UHD workflows. It helps in the final tone-mappings to understand MDCV in SDR.

Also, to clarify with historical info, "PQ10 becomes HDR10 when ST 2086 is added".  HDR10 is just metadata on PQ video essence.

**Comment by digitaltvguy** [comment]
Hi Chris, Are you able start off with the detail on chunk sizing and I'll work on the rest of the detail for ST 2086 and clli chunks.
