### ISSUE TITLE
Add CTA 861.3 MaxCLL & MaxFALL chunk

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#238]
We want to add a new chunk to show MaxCLL & MaxFALL as defined by CTA 861.3.

MaxCLL &MaxFALL are unsigned 16-bit numbers in units of 1 cd/m^2.
This new chunk is not required and can be omitted if the values are unknown.

This new chunk should come before the IDAT when provided.

In some places, arbitrary values are used. For example, the 99%tile might be used instead of the absolute max. This means we'll want to consider how much we want to specify or perhaps mention this discrepancy in a note.

What is a good name for the new chunk?

**Comment by digitaltvguy** [comment]
Can someone help me with the four-byte chunk-type-field values and component sizes and then I can build the rest of the spec?  Thx

ST 2086 Values required:

- Display Color Primaries:
- Red x,y (two values)
- Green x,y (two values)
- Blue x,y (two values)
- White Point x,y (two values)

- Max Mastering Display Luminance in nits
- Min Mastering Display Luminance in nits

MaxCLL/Max Fall (not part of ST 2086):
- Maximum Content Light Level (max pixel value in cd/m^2 )
- "Max" Frame Average Light Level (average cd/m^2 of all pixels)

**Comment by ProgramMax** [comment]
I'm not sure what help you would like. Could you elaborate?
I documented a good amount of the info here: https://github.com/w3c/PNG-spec/issues/236#issuecomment-1315060650
And now that the holidays are over I'll resume work on https://github.com/w3c/PNG-spec/pull/248 which should help give you a template.

**Comment by ProgramMax** [comment]
We decided on the name mLUm in the Jan 9th, 2023 meeting.

**Comment by svgeesus** [comment]
> Can someone help me with the four-byte chunk-type-field values 

>> **`mLUm` Maximum and Frame Average light levels.**

>> The four-byte chunk type field contains the hexadecimal values

>> 6D 4C 55 6D

The values are just the Unicode code points for the characters, which (for the ASCII range, in UTF-8) are identical to the 7-bit ASCII values. We recently changed from expressing these in decimal, to expressing them in hexadecimal.

> and component sizes and then I can build the rest of the spec? Thx

Following [what we did for mASt](https://github.com/w3c/PNG-spec/commit/7c0c9c15423ebacf300861413c7f9322448f08b0), each of the two should be 4 bytes with a scaling of 0.0001 cd/m<sup>2</sup> which allows a maximum luminance of (2^32) / 0.0001 = 429,496.7296 cd/m^2 (nits).

**Comment by digitaltvguy** [comment]
I've made an attempt to add mLum and also updated the definition for mAst.

**Comment by svgeesus** [comment]
"mDCv"  makes sense to me, too.

**Comment by svgeesus** [comment]
[`mDCv`](https://w3c.github.io/PNG-spec/#mDCv-chunk) and [`mLUm`](https://w3c.github.io/PNG-spec/#mLUm-chunk) now added to spec.

Oops, I see a nesting issue, `mLUm` is 11.3.3 but should be 11.3.2.8, and all the rest of section 11 is out from that point on.

**Comment by svgeesus** [comment]
I see the nesting was fixed. So, this is all done now, right?

**Comment by ProgramMax** [comment]
Yes, this is now done. I'll close it.

The nesting was fixed in https://github.com/w3c/PNG-spec/commit/1cbb1a006f2fc90c40f27537aad1549fd75f0615 on line 4099.
