### ISSUE TITLE
iTXt should be preferred

### ISSUE THREAD

**Issue by aphillips** [w3c/PNG-spec#239]
Section: Keywords and text strings
https://www.w3.org/TR/2022/WD-png-3-20221025/#11keywords

> In the [tEXt](https://www.w3.org/TR/2022/WD-png-3-20221025/#11tEXt) and [zTXt](https://www.w3.org/TR/2022/WD-png-3-20221025/#11zTXt) chunks, the text string associated with a keyword is restricted to the Latin-1 character set plus the linefeed character. Text strings in [zTXt](https://www.w3.org/TR/2022/WD-png-3-20221025/#11zTXt) are compressed into [zlib](https://www.w3.org/TR/2022/WD-png-3-20221025/#dfn-zlib) datastreams using [deflate](https://www.w3.org/TR/2022/WD-png-3-20221025/#dfn-deflate) compression (see [10.3 Other uses of compression](https://www.w3.org/TR/2022/WD-png-3-20221025/#10CompressionOtherUses)). The[ iTXt](https://www.w3.org/TR/2022/WD-png-3-20221025/#11iTXt) chunk can be used to convey characters outside the Latin-1 set. It uses the UTF-8 encoding [[rfc3629](https://www.w3.org/TR/2022/WD-png-3-20221025/#bib-rfc3629)]. There is an option to compress text strings in the [iTXt](https://www.w3.org/TR/2022/WD-png-3-20221025/#11iTXt) chunk.

The `iTXt` type, which is internationalized, should probably be more prominent in this paragraph and ideally should be recommended. This paragraph might say instead:

> The `iTXt` chunk uses the UTF-8 encoding and can be used to convey characters in any language. There is an option to compress text strings in the `iTXT` chunk. `iTXt` is RECOMMENDED for all text strings, as it supports Unicode. There are also `tEXt` and `zTXt` chunks, whose content is restricted to the printable Latin-1 character set plus the linefeed character. Text strings in `zTXt` are compressed into `zlib` datastreams using [deflate] compression (see 10.3 etc.)

Note the addition of the word "printable" to the description of the Latin-1 character set in my proposal: I think this is missing from the current text (I chose not to file a separate issue for this).

**Comment by svgeesus** [comment]
This seems like overall much better text to me, with no downsides.

**Comment by svgeesus** [comment]
@aphillips could you also please have a look at [12.9 Text chunk processing](https://w3c.github.io/PNG-spec/#12Text-chunk-processing) specifically this part which should also be reworded to emphasize `iTXT`:

> For the [tEXt](https://w3c.github.io/PNG-spec/#11tEXt) and [zTXt](https://w3c.github.io/PNG-spec/#11zTXt) chunks, PNG text strings are expected to use the Latin-1 character set. Encoders should avoid storing characters that are not defined in Latin-1, and should provide character code remapping if the local system's character set is not Latin-1. The [iTXt](https://w3c.github.io/PNG-spec/#11iTXt) chunk provides support for international text, represented using the UTF-8 encoding of UCS.

The "character code remapping" part especially, should probably be removed from the `tEXt` and `zTXt` chunks and instead the recommendation should be to convert the local non-Latin-1 character set to UTF-8 and use `iTXt`.

**Comment by aphillips** [comment]
@svgeesus Thanks for the pointer.

I read the "character code remapping" part as saying that locally encoded text (e.g. `MacOS Roman`) needs to be converted to Latin-1 before storing. But this is super unclear. I would suggest replacing the upper part of the paragraph (quoted here to see where I stopped):

> For the [tEXt](https://w3c.github.io/PNG-spec/#11tEXt) and [zTXt](https://w3c.github.io/PNG-spec/#11zTXt) chunks, PNG text strings are expected to use the Latin-1 character set. Encoders should avoid storing characters that are not defined in Latin-1, and should provide character code remapping if the local system's character set is not Latin-1. The [iTXt](https://w3c.github.io/PNG-spec/#11iTXt) chunk provides support for international text, represented using the UTF-8 encoding of UCS. Encoders should discourage the creation of single lines of text longer than 79 characters, in order to facilitate easy reading. It is recommended that text items less than 1024 bytes in size should be output using uncompressed text chunks. 

With something like:

> The `iTXt` chunk uses the UTF-8 encoding of Unicode and thus can store text in any language. The `tEXt` and `zTXt` chunks use the Latin-1 (ISO 8859-1) character encoding, which limits the range of characters that can be used in these chunks. Encoders **should** prefer `iTXt` to `tEXt` or `zTXt` chunks in order to allow a wide range of characters without data loss. Encoders **must** convert characters that use local [legacy character encodings](https://www.w3.org/TR/i18n-glossary/#def_legacy_character_encoding) to the appropriate encoding when storing text. Encoders **should** discourage the creation of single lines of text longer than 79 Unicode [code points](https://www.w3.org/TR/i18n-glossary/#def_code_point), in order to facilitate easy reading. It is **recommended** that text items less than 1024 bytes in size be stored using uncompressed text chunks.

Some notes on this suggestion:

1. I added links above to the I18N Glossary, which is a new effort by the I18N WG to provide convenient stable references to common character encoding terminology. This allows specs such as PNG to use I18N's preferred jargon without having to spend a ton of effort recapitulating or defining locally what is pretty dense and fiddly terminology. If you are using ReSpec you can add the directive `xref: ["i18n-glossary"]` to your config block and reference terminology using ReSpec's notation as-if these terms were defined locally.
2. I strengthened the Latin-1 requirement for *encoding* from "should" to "must". I don't know if this is appropriate, but storing byte values in an unknown encoding it not interoperable (cf. Postel's Law). 
3. I eliminated the really vague term "expected" regarding the use of Latin-1 in `tEXt` and `zTXt`. It is possible that there are PNG implementations that use other encodings for these chunks, but it isn't clear how those interoperate with other systems. There is also no text that I see in PNG about how to handle badly encoded text. Is this a gap?
4. The 79 character (code point) length limit seems fairly antiquated? The days of 80 column terminals are fairly far behind us. But I don't know what the state is for PNG implementations/tools and the 79 value might be baked into implementations? I used the term "code point" here because UTF-8 is a variable width (multibyte) encoding and I wanted to make clear that the recommended limit was in characters and not bytes, at least for the `iTXt` chunk.
5. There are a bunch of 2119 keywords in the original (and in my suggestion) and these are not giving the 2119 treatment. Is this intentional? I bolded the words in my suggestion to make them easier to find.

**Comment by palemieux** [comment]
> iTXt is RECOMMENDED for all text strings, as it supports Unicode.

How broad is iTXt coverage in players ?

**Comment by svgeesus** [comment]
Regarding RFC 2119, I think we need a whole pass to check this: the second edition used ISO terminology ("shal" etc nit RFC 2119).

The xref is giving me a respec warning about _normative reference to non-normative term_:

![image](https://user-images.githubusercontent.com/2506926/208464447-36b3dd90-4655-44b5-9e7c-14236fdd8ba1.png)

but I didn't see in the ReSpec docs how to mark a phrase or a link as non-normative (I'm much more familiar with Bikeshed, which all my other groups use)

**Comment by svgeesus** [comment]
@aphillips ok to close, now?

**Comment by aphillips** [comment]
Looks good to me. Please leave the "needs-resolution" label (the tools use it for tracking) but feel free to close.

**Comment by svgeesus** [comment]
Adobe Photoshop looks for XMP data, EXIF, and IPTC metadata. It does not seem to notice JPEG comments or any of `tEXt`, `zTXt` or `iTXt` (unless those contain XMP).

![image](https://user-images.githubusercontent.com/2506926/208938050-2a283372-4ca4-4c2d-9b52-4a5bb87dbcaa.png)

**Comment by svgeesus** [comment]
[exiftool]() seems to support `iTXt` well:

```
chris@SuperNomad:/mnt/c/Users/chris/Documents/PNG/PngSuite-2017jul19$ exiftool ctjn0g04.png
ExifTool Version Number         : 11.88
File Name                       : ctjn0g04.png
Directory                       : .
File Size                       : 941 bytes
File Modification Date/Time     : 2013:01:13 02:35:56+02:00
File Access Date/Time           : 2022:12:19 16:50:51+02:00
File Inode Change Date/Time     : 2022:11:06 23:45:33+02:00
File Permissions                : rwxrwxrwx
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 32
Image Height                    : 32
Bit Depth                       : 4
Color Type                      : Grayscale
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Gamma                           : 1
Title (ja)                      : PngSuite
Author (ja)                     : Willem van Schaik (willem@schaik.com)
Copyright (ja)                  : 著作権ウィレムヴァンシャイク、カナダ2011
Description (ja)                : PNG形式の様々な色の種類をテストするために作成されたイメージのセットのコンパイル。含ま れているのは透明度のフォーマットで、アルファチャネルを持つ、白黒、カラー、パレットです。すべてのビット深度が存在している仕様に従ったことができました。
Software (ja)                   : "pnmtopng"を使用してNeXTstation色上に作成されます。
Disclaimer (ja)                 : フリーウェア。
Image Size                      : 32x32
Megapixels                      : 0.001
```
