### ISSUE TITLE
ITU references have incorrect title?

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#249]
Our references to ITU-R BT.709, BT.2020, and H.273 all have the same title:
"ITU_____, SERIES H: AUDIOVISUAL AND MULTIMEDIA SYSTEMS Infrastructure of audiovisual services – Coding of moving video Coding-independent code points for video signal type identification"

I think this is only correct for H.273.
I think the others are BT series.
BT.2020 should perhaps be "Parameter values for ultra-high definition television systems for production and international programme exchange".
BT.709 should perhaps be "Parameter values for the HDTV standards for production and international programme exchange"

You can find these around line 140 of index.html.

Copy & paste error? Did I miss something?

**Comment by ProgramMax** [comment]
Maybe those titles should start with "ITU-R BT.709, Parameter values for..." I'm not sure. Or even "Recommendation ITU-R BT.2020, Parameter values for..." or some such.

**Comment by svgeesus** [comment]
> Copy & paste error? 

Don't know, Git blame now lists "apply HTML formatting as the commit for most lines :)
