### ISSUE TITLE
"Filter Selection" recommendations feel dated

### ISSUE THREAD

**Issue by DavidBuchanan314** [w3c/PNG-spec#256]
> For best compression of [truecolour](https://w3c.github.io/PNG-spec/#3truecolour) and greyscale images, the recommended approach is adaptive filtering in which a filter type is chosen for each scanline. The following simple heuristic has performed well in early tests: compute the output scanline using all five filters, and select the filter that gives the smallest sum of absolute values of outputs. (Consider the output bytes as signed differences for this test.) This method usually outperforms any single fixed filter type choice. However, it is likely that better heuristics will be found as more experience is gained with PNG.

This wording doesn't appear to have changed since the 1.0 spec, and it feels a bit dated.

Now that "more experience *has been* gained with PNG", is this still the best heuristic to recommend?

Perhaps it should be explicitly stated that more advanced heuristics (and meta-heuristics, and brute-force techniques) are known to exist (depending on scenario).

**Comment by ProgramMax** [comment]
Agreed that by now there is surely a better recommendation.
I personally do not have experience with the advanced heuristics you mentioned. I'm not in a good position to update this. I can look into it. But if anyone else (including you) have suggestions, pull requests are welcome. :D

**Comment by DavidBuchanan314** [comment]
Oops I just realised this is a duplicate of https://github.com/w3c/PNG-spec/issues/153
