### ISSUE TITLE
Figures 11-16 need to include the new mDCv and mLUm chunks

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#261]
Figures 11-16 show the chunks and need to include the two recently added chunks, mDCv and mLUm.

@palemieux I believe you had a suggestion for a handy tool to work on these figures?

@svgeesus Do you have a suggestion? I believe you worked on some other figures recently, right? Can I assign this to you?

**Comment by svgeesus** [comment]
The handy tool used to construct the existing figures was a plain text editor :)

**Comment by palemieux** [comment]
I think I was thinking of https://graphviz.org/

**Comment by ProgramMax** [comment]
Ohhh SVG. :D You so human-friendly.

**Comment by svgeesus** [comment]
`mLUm` is also missing from the [chunk ordering table](https://w3c.github.io/PNG-spec/#table53)

**Comment by svgeesus** [comment]
[PR](https://github.com/w3c/PNG-spec/pull/272)
