### ISSUE TITLE
Typo in E.1 Archive Sites URL (printed)

### ISSUE THREAD

**Issue by AramZS** [w3c/PNG-spec#265]
Very minor issue, but spotted during my privacy review: while the linked URL is correct [the link text for the archive URL at E.1](https://www.w3.org/TR/2022/WD-png-3-20221025/#E-Archive-sites) seems to have a typo. 

It is printed as `http://www.w3.org/TR/2022/WD-PNG-20221025"/`. The quote mark preceding the trailing slash appears to be in error?

**Comment by ProgramMax** [comment]
Thank you for catching that. [It looks like this has already been fixed.](https://w3c.github.io/PNG-spec/#E-Archive-sites) Should we take further action to retroactively fix that WD?

**Comment by AramZS** [comment]
@ProgramMax As long as you've got it fixed for the final version, that's not an issue I'd think! Just wanted to make sure it got caught before publication.

**Comment by ProgramMax** [comment]
Okay. I'll close the issue. Feel free to reopen if there is more we can do.
