### ISSUE TITLE
Should chunk names be mentioned in Scope?

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#269]
At the beginning of the document is the ["Scope" section](https://w3c.github.io/PNG-spec/#1Scope). It gives an overview of PNG.

It also calls out the mDCv and mLUm chunks by name. I feel like the specific chunk names should be left out of the general overview.
Or, if we leave them in they should link to their respective sections.

Thoughts?

**Comment by palemieux** [comment]
I think _This specification specifies a datastream and an associated file format, Portable Network Graphics (PNG, pronounced "ping"), for a [lossless](https://w3c.github.io/PNG-spec/#dfn-lossless), portable, compressed individual computer graphics image or frame-based animation, transmitted across the Internet._ would be sufficient as scope.

**Comment by ProgramMax** [comment]
I agree. To me, that defines the scope. The other stuff is more "how and why" which is already described in other sections.

I'll wait for others to chime in. Then I'll submit a pull request.

**Comment by svgeesus** [comment]
I agree with the tighter scope proposed by @palemieux
