### ISSUE TITLE
image/png registration points to Internet Draft

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#27]
The IANA [registration for `image/png`](https://www.iana.org/assignments/media-types/image/png) gives the defining specification as

> Internet-Draft draft-boutell-png-spec-04.txt

This should be updated to point to a more stable specification which didn't expire in 1996

**Comment by ProgramMax** [comment]
Would it be best to point to the [W3C spec](https://www.w3.org/TR/PNG) or [ISO spec](https://www.iso.org/standard/29581.html)?

Do we know if the contacts on the IANA doc are the people we should contact about this?

**Comment by ProgramMax** [comment]
I think it would be best to link to the W3C spec which is freely available.

Also, it looks like there is [good documentation for registering/updating IANA MIME types](https://www.w3.org/2020/01/registering-mediatypes).

> Note: Once a media type has been published by the IANA, the owner may request a change to its definition. The same procedure that would be appropriate for the original registration request is used to process a change request. See also Section 5.5, Change Procedures in BCP 13.

Also, from section 4.3 of that link:

> If your registration points to a dated version, request update of the registration via iana-mime-comment.

**Comment by svgeesus** [comment]
Yes, this is simple to do. I have been on the IANA MIME types list since 1992 so I am familiar with how it works.
Also the whole of [Annex A](https://w3c.github.io/PNG-spec/#A-Conventions) predates the modern IANA registration template and should be replaced by a filled-in IANA template.

Related to https://github.com/w3c/PNG-spec/issues/26 as we should register the MIME type for APNG as well (with a second filled-in template)

**Comment by svgeesus** [comment]
> Would it be best to point to the W3C spec or ISO spec?

The W3C spec, as you said, not only because it will be freely available but also because it will be updated sooner. And we don't yet know if the next version of PNG will have the same ISO number.

> Do we know if the contacts on the IANA doc are the people we should contact about this?

The [people listed](https://datatracker.ietf.org/doc/html/draft-boutell-png-spec-04#section-19) are (a subset of) the original PNG authors and were involved in creating the original PNG 1.0 [RFC 2083](https://datatracker.ietf.org/doc/html/rfc2083) in 1997.

**Comment by svgeesus** [comment]
From RFC 6838, [6.1.  Change Procedures](https://datatracker.ietf.org/doc/html/rfc6838#section-6.1)

>   Registrations may be updated in each registry by the same mechanism
   as required for an initial registration.  In cases where the original
   definition of the scheme is contained in an IESG-approved document,
   update of the specification also requires IESG approval.

So we need the full registration form for image/png, as an appendix

**Comment by svgeesus** [comment]
https://tools.iana.org/public-view/viewticket/1217157

**Comment by svgeesus** [comment]
The registration update is underway at IANA

**Comment by svgeesus** [comment]
IANA Expert review requested minor changes, which I made to the submission. I also [made them to our appendix](https://github.com/w3c/PNG-spec/commit/a38262fbab6efe31669f060dd9677092c23b4b10) to keep them in sync.

**Comment by svgeesus** [comment]
IANA review is complete, registration is updated, points to PNG WG as change controller

https://www.iana.org/assignments/media-types/image/png
https://www.iana.org/assignments/media-types/media-types.xhtml#image
