### ISSUE TITLE
Normative reference to informative definition

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#270]
In https://github.com/w3c/PNG-spec/commit/5fcfb473617986cd77002341b92f1d9ccd0078b9 the xref to "i18n-glossary" was added, along with `<a>legacy character encodings</a>` and `<a>code points</a>`.

Apparently, those two links are treated as normative references.
And inside i18n-glossary, those two terms are defined informatively.

This is causing ReSpec warnings.

If there is a proper fix, we should do that. I don't know how to do that.
We could do a per-instance fix of including `class="lint-ignore"` on each link.
We could also add a blanket `lint: { "informative-dfn": false }` to the ReSpec config.

Thoughts?

**Comment by ProgramMax** [comment]
An addition instance of `<a>legacy character encodings</a>` was added in https://github.com/w3c/PNG-spec/commit/f19b238d8ab51ebb3488ce0376433fecf05fd853

**Comment by svgeesus** [comment]
I'm not familiar enough with ReSpec to advise (I know how to do this in Bikeshed).

**Comment by svgeesus** [comment]
I think we should ask I18n WG why their term is informative. We use if normatively:

> Encoders must convert characters that use local `<a>`legacy character encodings`</a>`
      to the appropriate encoding when storing text.

so we can't make that section, or that sentence, informative.

**Comment by svgeesus** [comment]
Apparently "We could also add a blanket `lint: { "informative-dfn": false }` to the ReSpec config." is the correct thing.
