### ISSUE TITLE
Privacy Considerations section should be expanded to cover risks deriving from cross-origin communication channels

### ISSUE THREAD

**Issue by AramZS** [w3c/PNG-spec#282]
Thanks for bringing this proposal to PING for review. This issue comes from the [requested review](https://github.com/w3cping/privacy-request/issues/105). 

While you requested specific review over the additions to the specification, I do see the Privacy Considerations section (currently placed in the decoders section) is new. I thought it would be appropriate to review the entire specification as it currently stands with that in mind. 

I did not find any particular privacy considerations that PNG or its new sections introduces intrinsic to the specification itself, however, the nature of PNGs are that they are capable and intended to be transmitted across contexts that the browser does not normally intend to communicate with each other. With this in mind, there are some risks to privacy that the PNG introduces that are not problems of the specification but just general dangers that I think adopters should be aware of to some extent. 

I think it would be appropriate to expand the Privacy Considerations section to mention these risks, to assure the spec is clear and make it more useful to anyone considering privacy risks or handling PNGs. This is not considered an urgent issue. This is my first encounter with the PNG specification and my review included an extensive reading and review of some linked materials associated with security risks and some raised issues, so please excuse any issues with my explanation here and let me know if these need additional clarity. Some of these stem from existing well-documented security issues, but have particular privacy implications that I think are worth documenting. 

Issues that I believe should be explored in the context of the Privacy Considerations section for completeness's sake that, from my reading, appear to be present:

- A mix of encoding and decoding techniques can be used to alter the size of images[^1] in ways that may not be anticipated by the top level domain that embeds an image. This can allow for DOM manipulation that can be used to encode information read by the top level domain or a third party embedded script. This may allow for communication of user data across third and first party contexts, or between two third parties across a top level page to which they would not normally have access or communication capabilities. 
  - Additionally the spec currently notes: `When a fatal condition occurs, the decoder should fail immediately, signal an error to the user if appropriate, and optionally continue displaying any [image data](https://www.w3.org/TR/2022/WD-png-3-20221025/#dfn-image-data) already visible to the user (i.e. "fail gracefully"). The application as a whole need not terminate.` If errors are added intentionally during the encoding stage, a forced early termination can be used to intentionally alter heights or widths in the DOM or be used to imply other user properties and be used as a fingerprinting vector. 

- Encoding techniques could be used to render data at the point of request into the image itself[^1], using Edge-compute techniques this could be used to do on-the-fly encoding of data that can cross the 1st/3rd party barrier intended by browsers and without the knowledge of the user.  This can be used to reveal or transmit information about a user to parties which would not normally have access to that kind of communication. 

- The specification states that `A PNG datastream is composed of a collection of explicitly typed chunks. Chunks whose contents are defined by the specification could actually contain anything, including malicious code. But there is no known risk that such malicious code could be executed on the recipient's computer as a result of decoding the PNG image.` This is true in the security context[^2], it also implies that it is possible for such code to contain data about a user that would not normally be allowed to traverse across domain contexts, and the current state of browser technology is such that a PNG might be able to or allowed to traverse those contexts on the assumption that it is not a privacy or fingerprinting risk. However, there is a long history of images being used as tracking vectors. As the easy techniques become harder to execute and face a more serious privacy barrier and compute power becomes cheaper, I think it is possible that chunks may be set to contain user data in order to breach privacy expectations set by the browser and expected by the user. 

- Finally, [iTXt](https://www.w3.org/TR/2022/WD-png-3-20221025/#11iTXt), [tEXt](https://www.w3.org/TR/2022/WD-png-3-20221025/#11tEXt), and [zTXt](https://www.w3.org/TR/2022/WD-png-3-20221025/#11zTXt) chunks (mentioned in the security assessment), along with the eXif chunk which has been [moved into the "main body of this specification"](https://www.w3.org/TR/2022/WD-png-3-20221025/#changes-since-the-w3c-recommendation-of-10-november-2003-png-second-edition), can be used to encode user data and transmitted across systems or contexts in unexpected ways. This is a privacy concern, as user data could be transmitted in these chunks more easily, specifically, and these chunks are more open to common use. Of all concerns, these seems the most likely to arise as a technique for breaching privacy for a user and is--I would think--most important to mention. 

To be clear, I am not sure these issues are resolvable by the specification and I don't think anyone in PING expects these issues to result in changes to the technical elements of the specification. I think that the risks should be highlighted in the privacy section however, in order to assure they are known to those concerned with securing against such techniques in other contexts, or in other specs. 

Let me know if I can render any additional help or clarity here, or if I've got anything wrong in my understanding of the specification. Hopefully this assessment is helpful! 

[^1]: https://www.hackerfactor.com/blog/index.php?/archives/894-PNG-and-Hidden-Pixels.html
[^2]: https://github.com/w3c/PNG-spec/issues/170

**Comment by svgeesus** [comment]
> A mix of encoding and decoding techniques can be used to alter the size of images[1](https://github.com/w3c/PNG-spec/issues/282#user-content-fn-1-aaba87b3f92133efe05c712b1ba354dc) in ways that may not be anticipated by the top level domain that embeds an image. 

Right, several sloppy image cropping tools just re-write the width and height and don't re-encode the image data, so the original image data can be recovered by suitable tools. 

> This can allow for DOM manipulation that can be used to encode information read by the top level domain or a third party embedded script.

Could you expand on that a bit? Manipulation of the HTML DOM? The CSS OM? I'm wondering how, in-browser, the original data gets recovered by script, could you explain?

**Comment by annevk** [comment]
Could you expand on the threat model? There is a risk on the web for image data to leak across origins due to Spectre, but that's a security risk. (Without a great answer unfortunately.)

If two origins want to communicate they can already do so via CORS. They don't have to rely on PNG decoder specifics.

**Comment by svgeesus** [comment]
Pending answers to the more detailed cross-origin risks which have been suggested in this thread, I propose three simple additions to the Privacy Considerations which are well established:

> Some image editing tools have historically performed redaction by merely setting the alpha channel of the redacted area to zero, without also removing the actual image data. Users who rely solely on the visual appearance of such images run a privacy risk because the actual image data can be easily recovered.

> Similarly, some  image editing tools have historically performed clipping by rewriting the width and height in `IHDR` without re-encoding the image data, which thus extends beyond the new width and height and may be recovered.

> Images with `eXIf` chunks may contain automatically-included data, such as photographic GPS coordinates, which could be a privacy risk if the user is unaware that the PNG image contains this data. (Other image formats that contain EXIF, such as JPEG/JFIF, have the same privacy risk).

**Comment by svgeesus** [comment]
If we can get agreement on those three, I can add them into the Privacy Considerations while we wait to see if other things need to be added.

**Comment by svgeesus** [comment]
We also might want some _should not_ in the PNG Encoders section, about the clipping and redacting issues which are known bad practices.

**Comment by svgeesus** [comment]
@AramZS there were some questions for you, such as

> Could you expand on that a bit? Manipulation of the HTML DOM? The CSS OM? I'm wondering how, in-browser, the original data gets recovered by script, could you explain?

and the [comment by @annevk ](https://github.com/w3c/PNG-spec/issues/282#issuecomment-1511057184). Could you respond?

**Comment by svgeesus** [comment]
So the [suggested edits](https://github.com/w3c/PNG-spec/issues/282#issuecomment-1511449129) were added some time ago and [can be seen here](https://w3c.github.io/PNG-spec/#Privacy-considerations).

Questions have been asked of the original poster @AramZS and have gone unanswered for months.
