### ISSUE TITLE
Rename mLUm chunk to cLLi

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#283]
In our Mar 20th, 2023 meeting, @digitaltvguy made a great point that the mLUm chunk is called "CLLI" (Content Light Level Information) many places.

They listed some places where it is named CLLI:

- [QuickTime atom](https://developer.apple.com/av-foundation/High-Dynamic-Range-Metadata-for-Apple-Devices.pdf)
- [H.265 (but not abbreviated)](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-H.265-202108-I!!PDF-E&type=items)
- [MP4 registry](http://mp4ra.org/#/search)
- [and more](https://www.elecard.com/page/article_hdr)

We need to check as many PNG codecs as we can to make sure "mLUm" isn't yet adopted so we are in a good position to rename it.

**Comment by svgeesus** [comment]
> We need to check as many PNG codecs as we can to make sure "mLUm" isn't yet adopted so we are in a good position to rename it.

The longer we delay the more likely people are to implement it as `mLUm` or worse, create content with that chunk.

So lets swiftly go for `cLLi` and if we find some eager implementer who went for `mLUm`, get them to change their code.

**Comment by palemieux** [comment]
Ok we should use the opportunity to make the semantics consistent with these other specs:

* what does it mean if the values are zero
* what does it mean if the chunk is absent

We also need to emphasize that the value are not necessarily exactly equal to the mathematical calculations, i.e. they are nominal values.

**Comment by digitaltvguy** [comment]
Pull request has been created (mLUm tag changed to cLLi #285)

**Comment by digitaltvguy** [comment]
> Ok we should use the opportunity to make the semantics consistent with these other specs:
> 
> * what does it mean if the values are zero
> * what does it mean if the chunk is absent
> 
> We also need to emphasize that the value are not necessarily exactly equal to the mathematical calculations, i.e. they are nominal values.

I didn't see references which describes what to do if a value is absent. 

I did not that the value for MaxCLL could use some sort of algorithmic filter.

**Comment by digitaltvguy** [comment]
I've added to the definition for mDCv (for "should" use) and also added method for derived values from cICp and existing examples in ITU-T Series H Supp 19)

**Comment by svgeesus** [comment]
Closed by https://github.com/w3c/PNG-spec/pull/285 and https://github.com/w3c/PNG-spec/pull/288
