### ISSUE TITLE
Ambiguities about extra sample bits in bKGD, tRNS chunks

### ISSUE THREAD

**Issue by randy408** [w3c/PNG-spec#29]
What decoders should do about unexpected high bits in the RGB and grayscale samples of bKGD, tRNS chunks is not explicit, the ISO standard says the following:

>  two bytes per sample are used regardless of the image bit depth. If the image bit depth is less than 16, the least significant bits are used and the others are 0.

The wording is vague and has lead to diverging behavior across viewers. This affects both bKGD and tRNS chunks, this issue will focus on the more widely used tRNS chunk.

libpng masks off the high bits and issues a warning about out-range-values but will use the low bits regardless for transparency testing.

Firefox introduced a change that treats this as an error in 2008: https://hg.mozilla.org/mozilla-central/rev/4c61288079d2
The current revision of Firefox still has it and tests confirm this behavior: https://searchfox.org/mozilla-central/source/image/decoders/nsPNGDecoder.cpp#556-558

I have only observed libpng's behavior in Chrome and other browsers, image viewers.

The first attached image is a 128x128 8-bit grayscale image with (slightly lighter than) black borders, the bottom half is gray while the top half is black. It has a grayscale tRNS value of `0xFF00`, this makes the top half transparent on most implementations, except Firefox.
![blah](https://user-images.githubusercontent.com/33860634/130203919-3f81a322-45ee-4c75-8cca-366815034736.png)

The second image is the same except it has a tRNS value of `0x0000`, this is the intended way to specify black pixels as the transparent color. The top half is transparent even with Firefox.
![blah](https://user-images.githubusercontent.com/33860634/130204987-b1686ad9-0cd5-45bc-aac3-e91db6dd93e5.png)

The third image has no tRNS chunk and is how Firefox displays the first image on Windows. The workaround treats `0xFF00` as an invalid value and ignores it, leaving the top half black.
![blah](https://user-images.githubusercontent.com/33860634/130204712-1e2cd98a-24a7-4c9e-9702-bd49a0031fbc.png)

I would argue the standard's wording leans more towards ignoring the extra bits instead of treating it as an error, making Firefox less standard conformant than most.

Perhaps it should be clarified the presence of unexpected significant bits may signal an invalid sample, but the recommended behavior is to ignore the rest of the bits.

Past discussion:
* https://sourceforge.net/p/png-mng/mailman/png-mng-implement/thread/3.0.6.32.20080410073319.013c7e20%40mail.comcast.net/#msg19070368
* https://bugzilla.mozilla.org/show_bug.cgi?id=428045

**Comment by svgeesus** [comment]
Thanks for logging this issue. I agree that this is underspecified and should be clarified. Once that is done, it also needs some Web Platform tests so we can ensure that browsers are interoperable in this case.

**Comment by svgeesus** [comment]
Both cases are about the number of significant bits, for a value which is always stored in a 16bit field. This can be read as an (under-specified) requirement on encoders _and_ an (under-specified) requirement on decoders:

Encoders: since the insignificant bits won't be used they should have been set to zero. (But then you have to say how to handle the case where they weren't)

Decoders: since the insignificant bits are defined to be zero, mask them out so they won't be used regardless of how they were set.

But that interpretation needs discussion, and should also be tested for Web compatibility.

**Comment by svgeesus** [comment]
Also, because `bKGD` doesn't affect display of embedded images (like in a Web page), there has been less discussion about the similar bug there; but both cases of this wooly wording should be cleaned up.

**Comment by svgeesus** [comment]
The same wording was in PNG 1.2 and PNG 1.1

**Comment by svgeesus** [comment]
On tRNS, I believe we should continue to follow the Internet principle of "be strict in what you send, permissive in what you receive". So an encoder SHOULD set these bits to zero and a decoder MUST ignore these unused bits.

If the group agrees with that proposal, we wold need to open an issue on Firefox to get them to change their behavior.

**Comment by randy408** [comment]
If encoders should discard the top bits then libpng will also need a fix, it does not write a tRNS chunk if there are extra bits: https://github.com/glennrp/libpng/blob/v1.6.37/pngwutil.c#L1375

**Comment by ProgramMax** [comment]
In the Aug 8th, 2022 meeting we agreed that the spec wording "are 0" is bad.
At a minimum, the wording should clarify that those bits should be ignored by a decoder.
We can further push that the bits SHOULD be zero. This is what @svgeesus mentioned on Feb 20th, 2022.

@svgeesus, is it okay if I assign this to you?

**Comment by svgeesus** [comment]
[PR](https://github.com/w3c/PNG-spec/pull/260) changes wording to

>  If the image bit depth is less than 16, the least significant bits are used. Encoders should set the other bits to 0, and decoders must mask the other bits to 0 before the value is used.

in both places.

**Comment by svgeesus** [comment]
Fixed by https://github.com/w3c/PNG-spec/pull/260
