### ISSUE TITLE
Unused definition of "Greyscale with alpha"

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#298]
In 9a2ac909ae92872d134e81995f13389e8366f76a a new ReSpec warning arose:

'Found definition for "Greyscale with alpha", but nothing links to it. This is usually a spec bug!'

@palemieux you are perhaps best suited to handle this so I'm assigning it to you. If "Greyscale with alpha" is not referenced in the spec anywhere (Can that be right??) then perhaps we should just remove the definition? What do you think?

**Comment by svgeesus** [comment]
in [6.2 Alpha representation](https://w3c.github.io/PNG-spec/#6AlphaRepresentation) there should be a link to this definition, but the link is missing:

> [Truecolour with alpha](https://w3c.github.io/PNG-spec/#dfn-truecolour-with-alpha), **greyscale with alpha**: an alpha channel is part of the image array.

**Comment by palemieux** [comment]
Ah. It reminds me that we still have to go through the spec and add missing links to the definitions (using `<a></a>`) whenever appropriate.
