### ISSUE TITLE
Resolve PNG-EXTENSIONS / PNG-REGISTER naming

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#30]
The [PNG spec](https://www.w3.org/TR/PNG) has a link named [PNG-REGISTER]. This name is correctly referenced once in the spec.

Strangely, the fragment is named G-PNG-EXTENSIONS rather than G-PNG-REGISTER.
I suspect this is because it was once named PNG-EXTENSIONS. Elsewhere in the spec, there is one reference to [PNG-EXTENSIONS].
That reference name should be corrected. And then the fragment/links should be G-PNG-REGISTER instead of G-PNG-EXTENSIONS.

**Comment by svgeesus** [comment]
Related: [Where to find current list of registered extensions ?](https://github.com/w3c/PNG-spec/issues/8) in other words, where should the registered extensions live going forwards.

**Comment by svgeesus** [comment]
Correction done
