### ISSUE TITLE
Is Matrix Coefficients == 0 a requirement?

### ISSUE THREAD

**Issue by leo-barnes** [w3c/PNG-spec#302]
This is the text under `cICP`:

> The Matrix Coefficients value is equal to 0.
>
> NOTE
> A Matrix Coefficients value other than 0 signals a transformation between colour difference and RGB representations, which is not used in this International Standard since PNG images are RGB images.

I'm assuming this is meant to be normative, but there is no explicit shall/must. This means it could easily be missed, especially when writing compliance checkers (which typically search for all shalls/musts when adding the rules).

**Comment by ProgramMax** [comment]
Would those same tools be okay with this changing later?

PNG might later support color models other than RGB and 0 would no longer be a requirement. Knowing this now, is the SHALL/MUST wording still advisable?

**Comment by leo-barnes** [comment]
> Would those same tools be okay with this changing later?

This is more of a theoretical issue than a real one I guess. I know from experience with https://github.com/gpac/ComplianceWarden that it will only check for things that are explicitly marked as requirements (shall/must). It also checks for some *should*'s in order to warn if a file is not following recommendations.

But if something is not explicitly marked as a should or a shall, they don't know whether to add a check for it. It also clarifies to implementers what the expectation is.

We have had cases for HEIF/AVIF where spec updates relax some restrictions. Typically the compliance checker can be updated to take this into account. Older parsers may not be able to handle those files if they rely on those restrictions, but typically the change is done to align the spec with implementations, or the change is needed to allow some other feature that wouldn't be supported in older implementations in any case.

> PNG might later support color models other than RGB and 0 would no longer be a requirement. Knowing this now, is the SHALL/MUST wording still advisable?

Right, but are those other color models allowed now? If I create a file that uses a value other than 0, would it be considered to be a valid PNG file in this version of the spec?

I guess what I'm asking is:
If I write a new PNG parser from scratch, should I reject files with non-zero matrix coefficients, or should I try to handle them?

**Comment by ProgramMax** [comment]
Currently, RGB is the only supported color model in PNGs.
So I believe the SHALL/MUST wording would be correct for this current version of the spec. And I think a PNG parser should reject non-zero matrix coefficients because it would make no sense in the context of current PNGs.
(It is not yet clear how other color models would be supported, so a PNG parser trying to speculate on it might end up with something different from what a future spec does.)

I just wanted to make sure we weren't blocking off that path for later. It sounds like we aren't.
