### ISSUE TITLE
Testing `eXIf`, and CSS `image-orientation`

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#310]
CSS Images 3 includes [`image-orientation`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation) which requires EXIF data that specifies rotation to affect the display of images from CSS.

WPT has [some tests](https://wpt.fyi/results/css/css-images/image-orientation?label=experimental&label=master&aligned) in particular [image-orientation-exif-png.html](https://wpt.fyi/results/css/css-images/image-orientation/image-orientation-exif-png.html?label=experimental&label=master&aligned) which is currently only passed in Safari.

That test contrasts a PNG with `eXIf` before `IDAT` (which is required to be honored) with another PNG with `eXIf` after `IDAT` (which must not be honored). The trouble is that pngcheck shows the *before* PNG doesn't have an `eXIf` chunk at all!! It does however have a `zTXt` with an unregistered "Raw profile type exif" keyword.

```
chris@SuperNomad:/mnt/c/Users/chris/Documents/PNG/EXIF$ pngcheck -vv F-exif-early.png
File: F-exif-early.png (18826 bytes)
  chunk IHDR at offset 0x0000c, length 13
    400 x 400 image, 24-bit RGB, non-interlaced
  chunk zTXt at offset 0x00025, length 3573, keyword: Raw profile type exif
  chunk iCCP at offset 0x00e26, length 390
    profile name = ICC profile, compression method = 0 (deflate)
    compressed profile = 377 bytes
  chunk pHYs at offset 0x00fb8, length 9: 2835x2835 pixels/meter (72 dpi)
  chunk tIME at offset 0x00fcd, length 7: 16 Dec 2020 02:05:01 UTC
  chunk tEXt at offset 0x00fe0, length 25, keyword: Comment
  chunk IDAT at offset 0x01005, length 8192
    zlib: deflated, 32K window, maximum compression
  chunk IDAT at offset 0x03011, length 6501
  chunk IEND at offset 0x04982, length 0
No errors detected in F-exif-early.png (9 chunks, 96.1% compression).
chris@SuperNomad:/mnt/c/Users/chris/Documents/PNG/EXIF$ pngcheck -vv F-exif-late.png
File: F-exif-late.png (15343 bytes)
  chunk IHDR at offset 0x0000c, length 13
    400 x 400 image, 24-bit RGB, non-interlaced
  chunk iCCP at offset 0x00025, length 390
    profile name = ICC profile, compression method = 0 (deflate)
    compressed profile = 377 bytes
  chunk pHYs at offset 0x001b7, length 9: 2835x2835 pixels/meter (72 dpi)
  chunk tIME at offset 0x001cc, length 7: 16 Dec 2020 02:05:01 UTC
  chunk tEXt at offset 0x001df, length 25, keyword: Comment
  chunk IDAT at offset 0x00204, length 8192
    zlib: deflated, 32K window, maximum compression
  chunk IDAT at offset 0x02210, length 6501
  chunk eXIf at offset 0x03b81, length 90:  illegal (unless recently approved) unknown, public chunk
ERRORS DETECTED in F-exif-late.png
```

looking at the text chunks

```
chris@SuperNomad:/mnt/c/Users/chris/Documents/PNG/EXIF$ pngcheck -t F-exif*.png
File: F-exif-early.png (18826 bytes)
Raw profile type exif:
(compressed zTXt text)
Comment:
    Created with GIMP
OK: F-exif-early.png (400x400, 24-bit RGB, non-interlaced, 96.1%).

File: F-exif-late.png (15343 bytes)
Comment:
    Created with GIMP
F-exif-late.png  illegal (unless recently approved) unknown, public chunk eXIf
ERROR: F-exif-late.png

Errors were detected in 1 of the 2 files tested.
No errors were detected in 1 of the 2 files tested.
```

**Comment by svgeesus** [comment]
Since these images were created by GIMP, possibly related:

 - https://gitlab.gnome.org/GNOME/gimp/-/issues/8956
 - https://gitlab.gnome.org/GNOME/gimp/-/issues/7801

**Comment by svgeesus** [comment]
@fantasai [you created](https://github.com/web-platform-tests/wpt/commit/48e3fd2f4d41fa00640d27738bdda07db95594cc) that test; did you also create the PNG images? If so could you clarify how they were made, so that the `eXIf` chunk was before and after the image data, respectively?

**Comment by svgeesus** [comment]
![F-exif-early-forrealz](https://user-images.githubusercontent.com/2506926/236236041-46f528e8-f7b6-47a0-ac3c-9f24b7a2ac98.png)

This image was made from `F-exif-late.png` by loading it into TweakPNG and then moving the `eXIf` chunk up to right after `IHDR`.

```
chris@SuperNomad:/mnt/c/Users/chris/Documents/PNG/EXIF$ pngcheck -vv -f F-exif-early-forrealz.png
File: F-exif-early-forrealz.png (15343 bytes)
  chunk IHDR at offset 0x0000c, length 13
    400 x 400 image, 24-bit RGB, non-interlaced
  chunk eXIf at offset 0x00025, length 90:  illegal (unless recently approved) unknown, public chunk
  chunk iCCP at offset 0x0008b, length 390  chunk pHYs at offset 0x0021d, length 9  chunk tIME at offset 0x00232, length 7  chunk tEXt at offset 0x00245, length 25  chunk IDAT at offset 0x0026a, length 8192
    zlib: deflated, 32K window, maximum compression
  chunk IDAT at offset 0x02276, length 6501
  chunk IEND at offset 0x03be7, length 0
ERRORS DETECTED in F-exif-early-forrealz.png
```

The "error" is because pngcheck is unaware of the `eXIf` chunk.

```
chris@SuperNomad:/mnt/c/Users/chris/Documents/PNG/EXIF$ pngcheck -v
PNGcheck, version 2.3.0 of 7 July 2007,
   by Alexander Lehmann, Andreas Dilger and Greg Roelofs.

Test PNG, JNG or MNG image files for corruption, and print size/type info.
```

TweakPNG is also unaware of the `eXIf` chunk (but knows it is ancillary, and safe to copy)

**Comment by svgeesus** [comment]
I raised an issue on TweakPNG for supporting the newer chunks, including `eXIf`:

 - https://github.com/jsummers/tweakpng/issues/11

**Comment by svgeesus** [comment]
```chris@SuperNomad:/mnt/c/Users/chris/Documents/PNG/EXIF$ exiv2 -pa *real*.png
Exif.Image.Orientation                       Short       1  right, top
Exif.Image.XResolution                       Rational    1  72
Exif.Image.YResolution                       Rational    1  72
Exif.Image.ResolutionUnit                    Short       1  inch
Exif.Image.YCbCrPositioning                  Short       1  Centered
```

**Comment by svgeesus** [comment]
```
chris@SuperNomad:/mnt/c/Users/chris/Documents/PNG/EXIF$ exiv2 -pS *real*.png
STRUCTURE OF PNG FILE: F-exif-early-forrealz.png
 address | chunk |  length | data                           | checksum
       8 | IHDR  |      13 | ............                   | 0x0fdda19b
      33 | eXIf  |      90 | MM.*.......................... | 0x746ce56f
     135 | iCCP  |     390 | ICC profile..x.}.=H.P..OS."..; | 0xf0c3c3c0
     537 | pHYs  |       9 | .........                      | 0x009a9c18
     558 | tIME  |       7 | .......                        | 0xdd1c5917
     577 | tEXt  |      25 | Comment.Created with GIMP      | 0x57810e17
     614 | IDAT  |    8192 | x...il\.u....>.Im....EQ...U%.. | 0x15a34e38
    8818 | IDAT  |    6501 | ..v..........H6.....m;.N...... | 0xb6f29cea
   15331 | IEND  |       0 |                                | 0xae426082
```

**Comment by svgeesus** [comment]
So I am pretty confident that `F-exif-early-forrealz.png` is correct

**Comment by svgeesus** [comment]
I notice that an online [PNG Converter ](https://www.freeconvert.com/png-converter) has an option to rotate the image in accordance with the EXIF image orientation (and then, optionally remove that and other metadata)

![image](https://github.com/w3c/PNG-spec/assets/2506926/d7e9353b-5a23-4786-9f3b-c36b08854442)

So, for the implementation report, that is a tool which reads and makes use of the `eXIf` chunk.

**Comment by ProgramMax** [comment]
![exif-orientation-bottom-right](https://github.com/w3c/PNG-spec/assets/975115/02ea77f5-c342-4b60-9ddf-c30ce50f092a)
I created this test image by copying and pasting the eXIf chunk from that late-exif test image.

The raw image data has a red 100x100 square above a green 100x100 square. So any rotation should be obvious (and testable).

I don't see any rotation on FireFox, Chrome, or Safari.
Can you verify this test image is correct, too?

**Comment by svgeesus** [comment]
The image displayed in that GH comment has no exif.

> Chunk summary: IHDR, PLTE, tRNS, pHYs, IDAT, IEND

**Comment by ProgramMax** [comment]
![exif-orientation-bottom-right](https://github.com/w3c/PNG-spec/assets/975115/11ec6fcc-2f97-41de-ab13-a2cd1c155a53)
Whoops. I uploaded the wrong one.
Try this one.

**Comment by ProgramMax** [comment]
FWIW I see it rotated on Safari but not Firefox or Chrome.

**Comment by ProgramMax** [comment]
eXIf chunk is currently only browser-supported by Safari. Chromium and Firefox do not support it.
This made us consider marking eXIf 'at risk'.

Prior to the eXIf chunk, users could add a zTXt chunk with the exif keyword. This was also only browser-supported by Safari. Chromium and Firefox also do not support it.

Facebook processes the image, accepts the eXIf chunk, then removes the chunk but servers a rotated image.
When using the zTXt method, Facebook simply removes the chunk and ignores the exif keyword (so no rotation happens).

Twitter/X strips the eXIf & zTXt chunks, resulting in no rotation.

libpng already supports eXIf. I believe several non-browser programs do as well.

If we mark eXIf 'at risk' and move back to the zTXt method, the total change in support (from what I tested) is only the loss of functionality in Facebook. Browser will still behave the way they did.

I'm going to try to create a Chromium patch to support eXIf. If that lands, it would mean two independent browser implementations and puts eXIf back on a healthy path.

**Comment by ProgramMax** [comment]
*correction*: We can mark eXIf 'at risk' and move it back to an extension. This means both support via eXIf-extension and zTXt keyword.

Facebook support would then remain semi-okay, since it would continue to support the extension.

**Comment by svgeesus** [comment]
[Pull request to mark `eXIf` as at-risk](https://github.com/w3c/PNG-spec/pull/407)

**Comment by svgeesus** [comment]
Related: [CSS Images 3](https://drafts.csswg.org/css-images-3/#the-image-orientation) has a property `image-orientation` whose initial value (default value) is `from-image` which means:

> If the image has an orientation specified in its metadata, such as EXIF, this value computes to the angle that the metadata specifies is necessary to correctly orient the image.

[WPT results for `image-orientation`](https://wpt.fyi/results/css/css-images/image-orientation?label=experimental&label=master&aligned)

Note in particular that 

- [image-orientation-from-image-embedded-content.html](https://wpt.fyi/results/css/css-images/image-orientation/image-orientation-from-image-embedded-content.html?label=experimental&label=master&aligned)
- [image-orientation-from-image.html](https://wpt.fyi/results/css/css-images/image-orientation/image-orientation-from-image.html?label=master&label=experimental&aligned)

pass in Chrome, Edge, Firefox and Safari.

The difference? They all pull EXIF orientation data out of **JPEG** images. So the browsers already do this, and just need to look for EXIF in PNG images as well.

Related:

 - https://github.com/web-platform-tests/wpt/issues/18549

**Comment by svgeesus** [comment]
[chenney@chromium.org](https://bugs.chromium.org/u/2717106261) [wrote](https://bugs.chromium.org/p/chromium/issues/detail?id=1067846#c6):

> I would expect the EXIF information to be respected for PNG too, but I'm guessing everyone is using the same PNG decoder. This is a feature request for the Decoder team.

All we need is for the orientation to find it's way into the BitmapImage class. The PNGImageDecoder we have does not obtain the EXIF data from a PNG, so that's where the work would start, and end. All ImageDecoders have an orientation_ member but only the JPGImageDecoder ever sets it.

**Comment by ProgramMax** [comment]
There is already a WPT image orientation test using exif data from the zTXt chunk (which fails/passes as noted above):
[image-orientation-exif-png.html](https://wpt.fyi/results/css/css-images/image-orientation/image-orientation-exif-png.html?label=master&label=experimental&aligned)

**Comment by ProgramMax** [comment]
I believe this is now completed via https://wpt.fyi/results/png/exif-chunk.html?label=experimental&label=master&aligned
Can we close this issue?

**Comment by bogdan** [comment]
> I believe this is now completed via https://wpt.fyi/results/png/exif-chunk.html?label=experimental&label=master&aligned

I still see it doesn't work in firefox according to the link or live test:
https://ipfs.io/ipfs/bafybeibmn5gmdmrhb25wvcpyyyby4ifrtbcankex7nstqxnwkw7dk2nzq4

**Comment by svgeesus** [comment]
> I still see it doesn't work in firefox

By "completed" we meant "two independent implementations implement it", not "all implementations implement it, so it is baseline".

Firefox [plans to implement it in PNG, like they already do in JPEG](https://bugzilla.mozilla.org/show_bug.cgi?id=1682759) so it is expected to move to baseline.

**Comment by svgeesus** [comment]
@emilio I see Firefox [is marked as passing on wpt.fyi](https://wpt.fyi/results/png/exif-chunk.html?label=experimental&label=master&aligned) but the test fails on my (wide gamut) machine; I suspect this is a "test assumes sRGB screen" issue. Who should I ping to try to get this resolved?
