### ISSUE TITLE
Redundant note for fcTL

### ISSUE THREAD

**Issue by randy408** [w3c/PNG-spec#315]
At the end of `fcTL` chunk section (also present in the original APNG spec):

> Note, at the end of the fcTL chunk is a 32-bit CRC checksum. The checksum is calculated using the fcTL chunk and includes the 'fcTL' chunk type field.

This is true for all chunks and is therefore redundant.

**Comment by svgeesus** [comment]
I already had a comment in the source about that

```html
<!-- Not clear this para is needed, but the original specification had it -->
```

**Comment by svgeesus** [comment]
[PR to delete the note](https://github.com/w3c/PNG-spec/pull/316)
