### ISSUE TITLE
APNG section reads like a separate spec

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#317]
The APNG section talks about PNGs as if they are part of a separate spec. This makes sense, since the APNG wording comes from a separate spec.

Changing the wording to sound like it is all the same spec is not critical but would be nice.

**Comment by svgeesus** [comment]
Yes I was being fairly conservative in ensuring that all text from the stand-alone APNG spec had been included. But I agree, especially the [APNG introduction](https://w3c.github.io/PNG-spec/#introduction-0) could be better worded.

**Comment by svgeesus** [comment]
Would be fixed by https://github.com/w3c/PNG-spec/pull/325
