### ISSUE TITLE
MaxCLL and MaxFALL have no references

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#337]
Shouldn't we add a reference to [CTA 861.3-A-2016](https://webstore.ansi.org/standards/ansi/cta8612016-1636985#PDF) which is freely downloadable. It even has normative calculation methods in an annex.

**Comment by fintelia** [comment]
That annex is almost entirely just devoted to pseudo code for calculating averages and maximums. As far as how to calculate the light level values, the annex literally just says:
> convert the pixel’s non-linear (R’,G’,B’) values to linear values (R,G,B) calibrated to cd/m2

My understanding is that the non-linear to linear conversion can be done based on the contents of the cICP, sRGB, or gAMA chunks (perhaps with a fallback to gamma=2.2 or sRGB if none are present). 

But the proper strategy for then scaling the output from 0-1 range into a cd/m<sup>2</sup> value is less clear. The mDCv chunk is the only one other than cLLi mentioning cd/m<sup>2</sup>, so presumably the range is sourced from there. But do you convert by linearly interpolating between min and max mastering display luminance? Or perhaps the minimum luminance is only informational and you actually just multiply by the max display luminance? And what if that other chunk isn't present?

**Comment by michaeldsmith** [comment]
Our open-access SMPTE article [1] "On the Calculation and Usage of HDR Static Content Metadata" has some good discussion of how to set MaxCLL and MaxFALL 

[1] https://ieeexplore.ieee.org/document/9508136

**Comment by michaeldsmith** [comment]
In general, if you don't know how to set MaxCLL and MaxFALL, they should not be set.  Default values aren't helpful to the metadata ecosystem.  Any values that could be guessed at the file creation stage from other file properties could also likely be guessed in a decoding process from file properties.  If a value must be set and is setter does not know the correct value, there is a special value 0 that is reserved to mean "unknown".  If a default value were used instead, then a receiver that receives a file containing the default value won't know if that value is actually the correct value or if the creator didn't know what value to use and thus used the default value.  This creates an unreliable metadata ecosystem, which is avoided when using the value 0 that means "unknown".

**Comment by fintelia** [comment]
For a PNG encoder, I agree that it is worth emphasizing that saying "unknown" is far better than making up values. 

But for a PNG viewer, the plan is to say the contents of the cLLi chunk SHALL be used for tone mapping (#319). Which means that authors of decoders/viewers probably do need to know the meanings of the fields in the chunk if they want to follow that recommendation. But since the fields are defined in terms of how they're calculated, those authors need to understand the calculation process!

Even a short non-normative description and/or a link to an (ideally freely available) reference summarizing the ful conversion process between integer pixel values and light levels could go a long way

**Comment by svgeesus** [comment]
> the proper strategy for then scaling the output from 0-1 range into a cd/m2 value is less clear. 

It is only defined for color models that use an absolute luminance level. Which means BT.2100 PQ, (and J<sub>z</sub>a<sub>z</sub>b<sub>z</sub> and IC<sub>t</sub>C<sub>p</sub>, but those are not RGB models so can't be used in PNG anyway). So maybe we should be more explicit that these are for PQ content.

Most RGB models use relative luminance, and so they should not have MaxCLL and MaxFALL anyway.

**Comment by svgeesus** [comment]
> But the proper strategy for then scaling the output from 0-1 range into a cd/m2 value is less clear. The mDCv chunk is the only one other than cLLi mentioning cd/m2, so presumably the range is sourced from there. But do you convert by linearly interpolating between min and max mastering display luminance? Or perhaps the minimum luminance is only informational and you actually just multiply by the max display luminance? And what if that other chunk isn't present?

This is valuable feedback and we should ensure that other readers of the PNG specification don't have to similarly try to read between the lines to figure out how to do this. So, for a PNG decoder:

- `cLLi` is only useful for HDR content. It serves no function for SDR content.
- no, you _don't_ use the values from `mDCv` to do this.
- if there is `cICP` present **and**  `cICP` has the values `9 16 0 1` then your content is BT.2100 PQ and you can use the inverse of the PQ OETF to convert stored RGB values to absolute luminance
- otherwise, you can't; and the `cLLi` is probably there because someone didn't know what they were doing, so ignore it

A validator like PNGcheck could usefully give a warning if SDR or relative HDR content (BT.2100 HLG) contains `cLLi`.

OK let's do advice for a PNG encoder:

- is your content BT.2100 PQ?
- if so, you must write an `iCCP` chunk because `iCCP` can't usefully encode this, at least with version 4 ICC profiles
- do you know at least the chromaticities of the mastering display? If so write `mDCv` (and if you know the min an max luminances fill out those too, otherwise use 0 and 10,000) otherwise don't write that chunk
- do you know, or are you willing to calculate, the values for `cLLi`? If so copy them across (or caculate them) otherwise don't write that chunk

The spec has advice for when only one of MaxCLL or MaxFALL is known (write zero). **I would like to check that knowing only one is actually useful.** We should also say that if you don't know both, don't write the chunk at all rather than writing two zeroes.

**Comment by digitaltvguy** [comment]
> Shouldn't we add a reference to [CTA 861.3-A-2016](https://webstore.ansi.org/standards/ansi/cta8612016-1636985#PDF) which is freely downloadable. It even has normative calculation methods in an annex.

Created Pull request to address #337

**Comment by simontWork** [comment]
@svgeesus , did you mean:
"you must write an cICP chunk because iCCP can't usefully encode this" ?

**Comment by svgeesus** [comment]
> If it is, does this need the use of 0 for MaxFALL and MaxCLL mandated?

Is there a benefit in this rather than just not writing the chunk? Although perhaps, such a streaming encoder could go back and edit the values once the stream is ended.

**Comment by simontWork** [comment]
When discussing pixel luminance values in the specification, it is not obvious if the achromatic Y or the maximum of R, G or B for that pixel is meant.

**Comment by svgeesus** [comment]
In general luminance in te PNG spec should mean Y (calculated from linear-light R G B) as it does everywhere else in color science; and if we mean max(R' G' B') we should say so explicitly (and not call it luminance).

**Comment by michaeldsmith** [comment]
> @michaeldsmith PNG has a bunch of informative references to tutorial material and your article would make an excellent addition to that!

@svgeesus - please feel free to reference the article

**Comment by michaeldsmith** [comment]
> In general luminance in the PNG spec should mean Y (calculated from linear-light R G B) as it does everywhere else in color science; and if we mean max(R' G' B') we should say so explicitly (and not call it luminance).

@svgeesus - the MaxCLL and MaxFALL definitions use `max()` operator over the linear-light values R G B, not non-linear values R'G'B'.  But since `max()` is robust to monotonically increasing non-linearities like the PQ EOTF, I believe it is equivalent to compute `max(R,G,B)` or `max( PQ_EOTF(R'), PQ_EOTF(G'), PQ_EOTF(B') )` or `PQ_EOTF( max(R',G',B) )`.  

Instead of calling the resulting value a "luminance" we called the result a "light level" since it is not a luminance, except in some cases when the pixel values are on the gray axis pixels R=G=B.  I think if you use "MaxRGB light level", it is most clear when talking about MaxCLL and MaxFALL values.

@ simontWork @svgeesus - What are the units of the result of PQ_EOTF(R'), or PQ_EOTF(G') or PQ_EOTF(G') ? I think it is a bit awkward to talk about.  

In BT.2100, see Footnote 4b 

```
Note 4b – In this Recommendation, when referring to the luminance of a single colour component (RD, GD,
BD), it means the luminance of an equivalent achromatic signal with all three colour components having that
same value.
```

In SMPTE ST2084, there is a whole section 4.3 about it

![image](https://github.com/w3c/PNG-spec/assets/37905569/e899af79-e618-4622-b6cd-45ac31faea06)

**Comment by michaeldsmith** [comment]
> The spec has advice for when only one of MaxCLL or MaxFALL is known (write zero). **I would like to check that knowing only one is actually useful.** We should also say that if you don't know both, don't write the chunk at all rather than writing two zeroes.

I think knowing MaxCLL but not knowing MaxFALL is still useful, as the MaxCLL value can be used to set an upper bound for tonemapping input values.  For example, see the last section of the paper that I linked to above, Figure 14 shows how MaxCLL can be used for tonemapping.  

![image](https://github.com/w3c/PNG-spec/assets/37905569/f366156e-417f-40a8-9ff7-07aa8813d43c)

**Comment by svgeesus** [comment]
Fixed by https://github.com/w3c/PNG-spec/pull/351
