### ISSUE TITLE
mDCV chunk - use with SDR

### ISSUE THREAD

**Issue by simontWork** [w3c/PNG-spec#341]
"The mDCv chunk should be included for both PQ and SDR images"

What is meant by SDR image?  

One can use a cICP chunk to flag an sRGB image, which according to ICC has a fixed display white of 80 nits, or one can use an AdobeRGB cICC which has a fixed display white of 160.  Or is ITU-R BT.709 or BT.2020 meant?  This is a relative signal which only has a concept of display luminance applied when it is converted in a display (typically using an ITU-R BT.1886 EOTF), the reference level of which is given in ITU-R BT.2035.  Then there are systems based on ROMM, which is different again.

This sentence is not specific enough, nor do I think it is needed as the SDR signals either have reference white luminances which are fully defined or are relative signals.

"For SDR images, if mDCv display min/max luminance are unknown, the default characteristics can be derived from the values in [[ITU-T-Series-H-Supplement-19](https://www.w3.org/TR/2023/WD-png-3-20230720/#bib-itu-t-series-h-supplement-19)] Table 11 .”

Supplement 19 only gives values for BT.709 with a BT.1886 display under its reference viewing conditions (https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2035-0-201307-I!!PDF-E.pdf), not BT.2020, sRGB, AdobeRGB etc.

**Comment by simontWork** [comment]
Also, the link to supplement 19 in the draft spec is taking you to the previous version which does not have table 11.

**Comment by svgeesus** [comment]
Right, link is to a superseded version and should be updated to the current
https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=14652&lang=en

**Comment by ProgramMax** [comment]
Closed by #345
