### ISSUE TITLE
Narrow Range description

### ISSUE THREAD

**Issue by simontWork** [w3c/PNG-spec#342]
Can we change:
"In narrow range, momentary excursions defined as overshoots and undershoots exist below reference black and above nominal peak in uncontrolled lighting conditions, in order to preserve processing artifacts caused by video filtering/compression without clipping which can improve image quality during additional stages of processing and compression."
to:
"In narrow range, momentary excursions defined as overshoots and undershoots exist below reference black and above nominal peak in order to preserve processing artifacts caused by video filtering/compression or by uncontrolled lighting without clipping which can improve image quality during additional stages of processing and compression."

I think this better explains it as processing artefacts can occur on images/image sequences taken under controlled lighting scenarios, e.g. scaling filters ringing

**Comment by svgeesus** [comment]
I agree this is better wording

**Comment by simontWork** [comment]
Can probably drop the word video too, the processing can be applied to still images.

**Comment by svgeesus** [comment]
Agreed, resampling filters for still images can still exhibit ringing.

**Comment by ProgramMax** [comment]
Simon, don't forget to add yourself to the Editors list at the top of the document (in a JSON object).

**Comment by ProgramMax** [comment]
Oh, nevermind. I see that went in on https://github.com/w3c/PNG-spec/pull/345 Thank you!
