### ISSUE TITLE
Inconsistent colour / color

### ISSUE THREAD

**Issue by chrisn** [w3c/PNG-spec#374]
A minor issue, sorry. Should we pick one and use it throughout the spec?

**Comment by svgeesus** [comment]
The [original PNG spec from 1996](https://www.w3.org/TR/REC-png-961001) used color. see for example [2.2 Color values](https://www.w3.org/TR/REC-png-961001#DR.Color-values).

The reason being that the [W3C style guide](https://www.w3.org/Guide/manual-of-style/#Spelling) says, for spelling

> W3C uses U.S. English (e.g., "standardise" should read "standardize" and "behaviour" should read "behavior").

[PNG Second Edition in 2003](https://www.w3.org/TR/2003/REC-PNG-20031110/) used colour, see for example [4.2 Colour spaces](https://www.w3.org/TR/2003/REC-PNG-20031110/#4Concepts.ColourSpaces). 

The reason being that it was also published with identical content as ISO/IEC 15948:2003 (E) and ISO style rules require the use of International English (i.e. English without [Webster's US-specific spelling reform of 1828](https://www.quora.com/Why-do-a-large-number-of-words-in-the-Americans-version-of-the-English-language-differ-in-spelling-and-or-pronunciation))

( I remember when Lilley et. al _Colour in Computer Graphics_ was published in the UK in 1993 and made available online, I rapidly got a comment that "You have mis-spelled color, not just once, but throughout! Did you not think to use a spell checker?")

Of course whichever is chosen there will still be inconsistencies - If we use International English throughout, we will still refer to the International Color Consortium for example.

But I agree we should be consistent where possible and my preference would be to follow the W3C style guide and all other W3C specs and use the US English spelling.

Note that the links embed the spelling choices too:

https://www.w3.org/TR/REC-png-961001#DR.Color-values
https://www.w3.org/TR/2003/REC-PNG-20031110/#4Concepts.ColourSpaces

Given that the First Edition was in force for 1996-2003 and the Second Edition from 2003-2023 we should preserve link compatibility on fragment identifiers with the Second Edition, which we have been doing.

https://www.w3.org/TR/png-3/#4Concepts.ColourSpaces

**Comment by ProgramMax** [comment]
I feel like early in Third Edition development I read something (likely W3C?) saying to use international English. Maybe I'm misremembering.

In either case, I agree we should be consistent without breaking inbound links.

**Comment by svgeesus** [comment]
PR to use color in visible text, while preserving colour on inbound links.

 - https://github.com/w3c/PNG-spec/pull/411

**Comment by Crissov** [comment]
_Behaviour_ and _neighbour(ing)_ also still consistently spelled with an _u_. 

There are also some _-ise_ spellings:

* perceptual quantiser
* optimise
* standardised

The text consistently uses _grey_ and _greyscale_ instead of US _gray_.

**Comment by chrisn** [comment]
I added a commit to #411 to fix those, apart from grey/greyscale as I'm unsure on how to preserve incoming links.
