### ISSUE TITLE
Clarify that a frame with multiple fdAT's has only one sequence number 

### ISSUE THREAD

**Issue by fintelia** [w3c/PNG-spec#379]
The current spec isn't very clear whether the fdAT chunks contain only one sequence number per-frame or if every fdAT starts with a sequence number. The most clear indication is probably the confirmation that [zero length fdAT chunks are allowed](https://github.com/w3c/PNG-spec/issues/356), which is incompatible requiring all fdAT's to start with a sequence number.

The most confusing spot is probably Table 27. It seems to show the structure of a single fdAT chunk consisting of a 4-byte sequence number followed by n-bytes of frame data. However, my understanding is that structure is actually the breakdown _after concatenating all the fdAT's for the frame_:

> fdAT chunk contents:
> Name | Size
> -- | --
> sequence_number | 4 bytes
> frame_data | n bytes

The subsequent text talks about the concatenation of multiple fdAT chunks, but completely omits any mention sequence numbers:

> The compressed datastream is then the concatenation of the contents of the data fields of all the fdAT chunks within a frame          (noting that data fields may be of zero length).

**Comment by rayrobdod** [comment]
[Section 4.9.2 Sequence Numbers](https://w3c.github.io/PNG-spec/#4Concepts.APNGSequence) indicates that the reason for the sequence number is to make sure that the chunks have not been reordered. The sequence number could not do this if second `fdAT`s for a frame were missing a sequence number, or if second `fdAT`s for a frame has the same sequence number as the first `fdAT` for the frame. Additionally, the tables in the sequence number sections are examples that has `fdAT` chunks split across frames and indicates that it is the chunks that are numbered, not the frames.

In the context of "there is a `sequence_number` field and a `frame_data` field", the "concatenation of the contents of the data fields" means the concatenation of the `frame_data` fields. Still, the [Chunk fields table](https://w3c.github.io/PNG-spec/#table51)) has a "data field", and based on that the "concatenation of the contents of the data fields" would include the sequence numbers.

Would changing the "fdAT Frame Data Chunk Section" to say "The compressed datastream is then the concatenation of the contents of the frame_data fields of all the fdAT chunks within a frame (noting that frame_data fields may be of zero length)" be clearer?

**Comment by fintelia** [comment]
> Would changing the "fdAT Frame Data Chunk Section" to say "The compressed datastream is then the concatenation of the contents of the frame_data fields of all the fdAT chunks within a frame (noting that frame_data fields may be of zero length)" be clearer?

Yes, that would be more clear.

**Comment by randy408** [comment]
I believe "zero-length fdAT" is a mistake introduced with https://github.com/w3c/PNG-spec/pull/363.

@svgeesus If a valid fdAT chunk requires a sequence number that implies a size of at least 4 bytes, at least that's how I see it

**Comment by svgeesus** [comment]
Yeah this:

> The compressed datastream is then the concatenation of the contents of the data fields of all the fdAT chunks

should really be this:

> The compressed datastream is then the concatenation of the contents of the `frame_data` fields of all the fdAT chunks

**Comment by svgeesus** [comment]
Sequence number increments with each chunk, so all the `fDAT` chunks for a given frame do not have the same sequence number. This is because the PNG spec disallows chunk ordering restrictions on ancillary chunks.

**Comment by svgeesus** [comment]
> I'd also maintain that a fdAT chunk with length=4 should not be called a "zero-length fdAT", but I think I may be a bit late on that one

No, I think we can clarify that one.

**Comment by svgeesus** [comment]
> The most confusing spot is probably Table 27. It seems to show the structure of a single fdAT chunk consisting of a 4-byte sequence number followed by n-bytes of frame data. 

Correct.

However, my understanding is that structure is actually the breakdown after concatenating all the fdAT's for the frame

Incorrect, and I don't see how that follows from the spec.

> The subsequent text talks about the concatenation of multiple fdAT chunks, but completely omits any mention sequence numbers:

I suspect that you missed [4.9.2 Sequence numbers](https://w3c.github.io/PNG-spec/#4Concepts.APNGSequence):

> The [fcTL](https://w3c.github.io/PNG-spec/#fcTL-chunk) and [fdAT](https://w3c.github.io/PNG-spec/#fdAT-chunk) chunks have a zero-based, 4 byte sequence number. Both chunk types share the sequence. The purpose of this number is to detect (and optionally correct) sequence errors in an Animated PNG, since this specification does not impose ordering restrictions on ancillary chunks.

> The first [fcTL](https://w3c.github.io/PNG-spec/#fcTL-chunk) chunk shall contain sequence number 0, and the sequence numbers in the remaining [fcTL](https://w3c.github.io/PNG-spec/#fcTL-chunk) and [fdAT](https://w3c.github.io/PNG-spec/#fdAT-chunk) chunks shall be in ascending order, with no gaps or duplicates.

and thus, we should link to that section when mentioning sequence numbers, so other readers don't miss it.

**Comment by svgeesus** [comment]
I suspect the ambiguity crept in because the `fdAT` description contains a too-literal copy of text from the [`IDAT`](https://w3c.github.io/PNG-spec/#11IDAT) chunk:

> The compressed datastream is then the concatenation of the contents of the data fields of all the IDAT chunks (noting that data fields [may be of zero length](https://w3c.github.io/PNG-spec/#zero-length-data)).
