### ISSUE TITLE
Add more complete definition of Chunk types four-byte sequences (four 1-byte ASCII abbreviation)

### ISSUE THREAD

**Issue by digitaltvguy** [w3c/PNG-spec#396]
Chunk types are four-byte sequences **_composed of four 1-byte values chosen so that they abbreviate a logical,_** readable label when interpreted in the ISO 646.IRV:1991 [[ISO646](https://www.w3.org/TR/png-3/#bib-iso646)] character set.

**Comment by svgeesus** [comment]
Yes, it doesn't actually say that anywhere, and should.

**Comment by DavidBuchanan314** [comment]
It might be worth explicitly noting that the characters are stored in "correct" order. There are many formats out there that use the reverse order.

**Comment by svgeesus** [comment]
What we [do have](https://w3c.github.io/PNG-spec/#4Concepts.FormatTypes) is:

> Chunk types are four-byte sequences chosen so that they correspond to readable labels when interpreted in the ISO 646.IRV:1991 [[ISO646](https://w3c.github.io/PNG-spec/#bib-iso646)] character set.

**Comment by jbowler** [comment]
I think the original wording was deliberately written not to be biased towards a particular group of languages.  It's equally understandable in any language and it is precise.  The choice of encoding is, of course, colonial at best but we may perhaps be forgiven for using our own language.

**Comment by svgeesus** [comment]
Yes, I think that what we already have is clear enough.

Close?

**Comment by ProgramMax** [comment]
Closing. But happy to re-open if there are votes for that.
