### ISSUE TITLE
Right to be forgotten

### ISSUE THREAD

**Issue by jbowler** [w3c/PNG-spec#399]
Please remove my name from current editions of this specification.  You are free to remove my name from everything but I am directly and unambiguously asking for my name to be remove as an "Author" of the current edition.

**Comment by ProgramMax** [comment]
I have created a pull request to honor your wishes.

I want to mention something which might add some clarify though:
The "authors" section refers to the [original authors of the original spec]( http://www.libpng.org/pub/png/spec/1.2/PNG-Credits.html), not the current edition's contributors.

The current edition's contributors are listed under "editors". And former edition editors are thus under "former editors".

If that changes your wishes, we'll leave things as-is and close the pull request.
If that doesn't change your wishes, we'll continue with the pull request.
