### ISSUE TITLE
Inconsistent use of US vs. International English

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#4]
Raised by: Susan Lesch
Originally raised [8 Jul 2003](https://lists.w3.org/Archives/Public/png-group/2003Jul/0001.html)

> Are you still accepting comments? If you are, I will try to read thePNG Proposed Recommendation [1] on Tuesday-Wednesday. > Here are results of spell checking.

> Does this project require UK English? I have only the old Directives
> Part 3 3rd edition which says: "The following reference works for
> language are suggested: - for English, The Shorter Oxford English
> Dictionary and The Concise Oxford Dictionary...." W3C on the other hand
> uses US English [2]. I imagine it's bad form to point these out but
> here goes (they weren't in the 1996 edition).

> s/neighbouring/neighboring/
> s/colour/color/
> s/defence/defence/
> s/truecolour/truecolor/
> s/neighbour/neighbor/
> s/favour/favor/
> s/behaviour/behavior/
> s/honour/honor/
> s/organisations/organizations/
> s/metre/meter/

> minor typos
> ===========
> There is one "grayscale" (the rest are greyscale; either is fine).
> s/obseletes/obsoletes/
> s/orginal/original/
> s/internet/Internet/

> Editorial changes says, "The document has been reformatted according to
> the requirements of ISO." Is justified text required? I think unless
> one has a fancy high resolution set up this is quite hard to read
> justified. What is the source of the style sheet [3]? Unless it is
> ISO, 'text-align: justify;' could be one huge rule for all your
> selectors, and then be commented out for W3C.

> Also I wondered if you had looked at the Manual of Style suggestion
> for references [4]. The titles ought to be the link.

> I just happened to see the reference for RFC 2070 should read:
>    Yergeau, F., Nicol, G., Adams, G., Du&uuml;rst, M.,
> (note the commas)

> More comments later this week if you would still accept them.

> [1]http://www.w3.org/TR/2003/PR-PNG-20030520/  <http://www.w3.org/TR/2003/PR-PNG-20030520/>
> [2]http://www.w3.org/2001/06/manual/#Spelling  <http://www.w3.org/2001/06/manual/#Spelling>
> [3]http://www.w3.org/TR/2003/PR-PNG-20030520/isostyle.css  <http://www.w3.org/TR/2003/PR-PNG-20030520/isostyle.css>
> [4]http://www.w3.org/2001/06/manual/#ref-section  <http://www.w3.org/2001/06/manual/#ref-section>

**Comment by svgeesus** [comment]
> Does this project require UK English?

The ISO specifications require International English, as used in the UK, Canada, Australia, New Zealand, India, and many other countries. It differs from US English in not having adopted the US-specific spelling reforms.

Thanks for pointing out the occasional uses of US English, which should be corrected to International English.

**Comment by ProgramMax** [comment]
Adding a bit more info:
"orginal" was not in the doc and didn't need correction.

However, I'm going to re-open because there are still occurrences of US spellings, such as:
color -> colour
license -> licence
annex -> annexe
program(s) -> programme(s)
Possibly artifact -> artefact but "artifact" is now an accepted spelling in many International English publications.

(Note: Leave "catalog" as it is a title of a reference. Do not change it to the International English "catalogue".)

**Comment by ProgramMax** [comment]
I forgot to mention, this part might still be relevant:

> Also I wondered if you had looked at the Manual of Style suggestion
> for references [4]. The titles ought to be the link.

> [4]http://www.w3.org/2001/06/manual/#ref-section

There is both the Normative references section and the Bibliography section where this might apply.

**Comment by ProgramMax** [comment]
A UK friend of mine said that "programme" is okay for TV shows but old fashioned for computer programs.

And "licence" is the noun (driving licence) and "license" is the verb (to license someone to drive).
Same for "annexe" being a noun. However, "annex" is apparently becoming standard.

Whoever works on this will likely end up putting in a good deal of research / work that won't be obviously visible. :)

**Comment by ProgramMax** [comment]
Is "truecolor" one word? I see it used as such in the spec several times. I have this feeling that it was once one word but now might be two. (Either way, I think the "colour" spelling applies.)
