### ISSUE TITLE
HDR10 reference

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#413]
The reference [[HDR10]] doesn't resolve. Does  this look correct?

ANSI/SCTE 215-1-1 2020b
HEVC Video Constraints for Cable Television Part 1-1 HDR10 Coding
https://www.scte.org/documents/560/ANSI_SCTE-215-1-1-2020b-1616683883836.pdf

**Comment by svgeesus** [comment]
9FROM https://www.scte.org/standards/library/catalog/scte-215-1-1-hevc-video-constraints-for-cable-television-part-1-1-hdr/ )

**Comment by svgeesus** [comment]
Is that the right reference for HDR10?

**Comment by chrisn** [comment]
I don't know that that spec is definitive, AIUI it originates from CEA: https://web.archive.org/web/20190611151620/https://www.cta.tech/News/Press-Releases/2015/August/CEA-Defines-%E2%80%98HDR-Compatible%E2%80%99-Displays.aspx

**Comment by chrisn** [comment]
I don't know that mentioning HDR10 is essential for the PNG spec, so could we simply remove "and is commonly then called HDR10 (PQ with ST 2086 static metadata)". The spec doesn't need to be a tutorial on HDR.

**Comment by svgeesus** [comment]
I agree it doesn't need to be a tutorial, but the reference to HDR10 seems to be useful. We could simply cite

https://en.wikipedia.org/wiki/HDR10

as an informative reference.

**Comment by chrisn** [comment]
That sounds good to me, yes.

**Comment by simontWork** [comment]
I think technically, it should be:

HDR10 (PQ with ST 2086 static metadata, MaxFALL and MaxCLL)

as the last 2 are required by HDR10, but not defined in ST 2086
