### ISSUE TITLE
Latest H.273 is not free

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#428]
From the PNG spec, the reference to H.273 points to

https://www.itu.int/rec/T-REC-H.273

From that page, there is a link to [H.273 (07/21)](https://www.itu.int/rec/recommendation.asp?lang=en&parent=T-REC-H.273-202107-S) which still works and is free. But there is also a link to a new version, [H.273 (09/23)](https://www.itu.int/rec/recommendation.asp?lang=en&parent=T-REC-H.273-202309-P) which says **Document restricted to [TIES users](http://www.itu.int/TIES) [ITU-T]**.

Does anyone know, is that a temporary situation (that version is described as _prepublished_,) or is this a new, non-free policy coming into effect?

**Comment by svgeesus** [comment]
[This page](https://www.itu.int/itu-t/recommendations/rec.aspx?rec=15650) says H.273 2021 is superseded and the 2023 version is "in force".

I have found a [description of the changes between 2021 and 2023](https://www.itu.int/itu-t/workprog/wp_item.aspx?isn=18689), which does not seem it impacts PNG as it is solely for non-RGB formats:

> This revised Rec. ITU-T H.273 adds the specification of code point identifiers for YCgCo-R colour representation with equal luma and chroma bit depths and for the colour representation specified in SMPTE ST 2128. The new code points for YCgCo-R are referred to as YCgCo-Re and YCgCo-Ro, where the number of bits added to a source RGB bit depth is 2 (i.e., even) and 1 (i.e., odd), respectively. SMPTE ST 2128 specifies a colour representation referred to as IPT-PQ-C2 This Recommendation was developed jointly with ISO/IEC JTC 1, Information technology, Subcommittee SC 29, Coding of audio, picture, multimedia and hypermedia information, and Rec. ITU-T H.273 is maintained as technically aligned twin text with ISO/IEC 23091-2. The changes specified in this version correspond to the technical content of a not-yet-published future (third) edition of ISO/IEC 23091-2.

**Comment by digitaltvguy** [comment]
Superseded and in-force but not available to general public yet without a TIES login.  I’m not sure when it will be fully released (pre-published).

From: Chris Lilley ***@***.***>
Date: Saturday, February 24, 2024 at 5:28 PM
To: w3c/PNG-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [w3c/PNG-spec] Latest H.273 is not free (Issue #428)

This page<https://urldefense.com/v3/__https:/www.itu.int/itu-t/recommendations/rec.aspx?rec=15650__;!!PIZeeW5wscynRQ!qTEatZumwP4OBd4ORQ8eX6s7A239oqb-II2HNwsPRWWI8nchBAWyFv3ltuJhaiPDHt-YEl-TrnDjxrNlpZ88fiuyHg$> says H.273 2021 is superseded and the 2023 version is "in force".

I have found a description of the changes between 2021 and 2023<https://urldefense.com/v3/__https:/www.itu.int/itu-t/workprog/wp_item.aspx?isn=18689__;!!PIZeeW5wscynRQ!qTEatZumwP4OBd4ORQ8eX6s7A239oqb-II2HNwsPRWWI8nchBAWyFv3ltuJhaiPDHt-YEl-TrnDjxrNlpZ-MvhRREQ$>, which does not seem it impacts PNG as it is solely for non-RGB formats:

This revised Rec. ITU-T H.273 adds the specification of code point identifiers for YCgCo-R colour representation with equal luma and chroma bit depths and for the colour representation specified in SMPTE ST 2128. The new code points for YCgCo-R are referred to as YCgCo-Re and YCgCo-Ro, where the number of bits added to a source RGB bit depth is 2 (i.e., even) and 1 (i.e., odd), respectively. SMPTE ST 2128 specifies a colour representation referred to as IPT-PQ-C2 This Recommendation was developed jointly with ISO/IEC JTC 1, Information technology, Subcommittee SC 29, Coding of audio, picture, multimedia and hypermedia information, and Rec. ITU-T H.273 is maintained as technically aligned twin text with ISO/IEC 23091-2. The changes specified in this version correspond to the technical content of a not-yet-published future (third) edition of ISO/IEC 23091-2.

**Comment by svgeesus** [comment]
_(whoops)_
