### ISSUE TITLE
Register keyword XML:com.adobe.xmp

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#43]
From glennrp, PNG/MNG discussion list, 2017-01-15, 05:59

> I found the discussion in my own archives, thread 10/08/09 through 11/02/09:
> [png-mng-misc] PNG and XMP already a way to consider storing metadata?
> plus two messages on 10/09/09 entitled
> [png-mng-misc] Proposed "XML:com.adobe.xmp" PNG keyword
> 
> http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart3.pdf
> 
> paragraph 1.1.5 table 9 PNG data format
> 
> length
> "iTXt"
> keyword "XML:com.adobe.xmp"
> NULL (keyword terminator)
> 0x00 compression flag
> 0x00 compression method
> NULL (language tag terminator)
> NULL (translated keyword terminator)
> text (UTF-8 encoded XMP packet)
> CRC
> 
> Only one XMP packet allowed in a PNG.
> Can appear anywhere but recommended to be at the beginning.
> Adobe recommends using compression flag 0x00 (uncompressed)
> and compression method 0x00 (ignored in uncompressed iTXt).
> 
> Prior discussion on png-mng-misc, thread beginning 10/08/09 through 11/02/09:
> [png-mng-misc] PNG and XMP already a way to consider storing metadata?
> plus two messages on 10/09/09 entitled
> [png-mng-misc] Proposed "XML:com.adobe.xmp" PNG keyword
> 
> 
> Our 2009 discussion ended with Cosmin's proposal:
> 
>   It is proposed to register the following new text keyword for
>   use in PNG files:
> 
>   XML:com.adobe.xmp
>   Extensible Metadata Platform (XMP) information, formatted
>   as required by the XMP specification [XMP].  The use of iTXt,
>   with Compression Flag set to 0, and both Language Tag and
>   Translated Keyword set to the null string, are recommended
>   for XMP compliance.
> 
>   References
>   [XMP]
>      Adobe Systems Inc., "XMP Specification", September 2005.
>      http://www.adobe.com/devnet/xmp/
> 
> We didn't vote on it because we were busy with libpng-1.4.0
> release, and then never got back to it.

**Comment by svgeesus** [comment]
So at various times between 2009 and 2015 it was proposed for registration, but that never quite happened. The proposed registration text from Cosmin Truta looks very reasonable to me.

**Comment by ProgramMax** [comment]
I attempted to assign this to @lrosenthol but was unable to.
@svgeesus, do we need to add Leonard to the group somehow?

**Comment by svgeesus** [comment]
Hmm try again? Should be working now

**Comment by svgeesus** [comment]
Okay I see @lrosenthol in the drop-down but it doesn't "take". Odd.

**Comment by svgeesus** [comment]
Tried again and now it does.
