### ISSUE TITLE
cICP *video* full range flag?

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#431]
The 4th byte of cICP is titled the "video" full range flag.
This flag applies to still images, too.

This is because H.273 calls it video full range flag. That way PNG is consistent with H.273, which it references.

But is H.273 generally only thought of in video contexts?
Is it worth adding confusion to PNG ("video??") in order to reduce confusion in PNG ("Ah okay. This matches that part of H.273.") in this way?

**Comment by svgeesus** [comment]
I think it is worth an explanatory note.

**Comment by digitaltvguy** [comment]
I threw in a comment for video full range flag in an associated branch. Is it sufficient?
