### ISSUE TITLE
SMPTE RP 2077 is not freely available

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#433]
SMPTE RP 2077 "Full-Range Image Mapping" is not freely available "red "you do not have access to this PDF".

![image](https://github.com/w3c/PNG-spec/assets/2506926/ef384a95-b533-4d32-b64f-8785a7d94947)

I recall we asked SMPTE to make some docs freely available and they graciously obliged; I don't remember offhand if this was in the set or not.

**Comment by digitaltvguy** [comment]
SMPTE standards are now free for members:

https:/my.smpte.org/<https://urldefense.com/v3/__https:/my.smpte.org/__;!!PIZeeW5wscynRQ!oeHLgIJG25t9d5f5AAcEAxXJbMtxqVkxWCBCjj3xA8qE-zWof9h5PnGh5NeZdx56otL1M_JJYaV6MTuxygPU$>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Chris Lilley ***@***.***>
Sent: Friday, March 1, 2024 11:17:31 AM
To: w3c/PNG-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [w3c/PNG-spec] SMPTE RP 2077 is not freely available (Issue #433)


SMPTE RP 2077 "Full-Range Image Mapping" is not freely available "red "you do not have access to this PDF".

image.png (view on web)<https://urldefense.com/v3/__https://github.com/w3c/PNG-spec/assets/2506926/ef384a95-b533-4d32-b64f-8785a7d94947__;!!PIZeeW5wscynRQ!uDH64hkQWBKV_2lgnVUthoID0ka8zSVtt45t-N0TgtG10nKagK3xsUDQ3km8Arp25JpWlr0mI6ypQQru6QDf5CRI_g$>

I recall we asked SMPTE to make some docs freely available and they graciously obliged; I don't remember offhand if this was in the set or not.

**Comment by digitaltvguy** [comment]
EBU r103 also has a handy graphic:

https://tech.ebu.ch/docs/r/r103.pdf

***@***.***

From: Chris Lilley ***@***.***>
Date: Friday, March 1, 2024 at 11:18 AM
To: w3c/PNG-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [w3c/PNG-spec] SMPTE RP 2077 is not freely available (Issue #433)

SMPTE RP 2077 "Full-Range Image Mapping" is not freely available "red "you do not have access to this PDF".

image.png (view on web)<https://urldefense.com/v3/__https:/github.com/w3c/PNG-spec/assets/2506926/ef384a95-b533-4d32-b64f-8785a7d94947__;!!PIZeeW5wscynRQ!uDH64hkQWBKV_2lgnVUthoID0ka8zSVtt45t-N0TgtG10nKagK3xsUDQ3km8Arp25JpWlr0mI6ypQQru6QDf5CRI_g$>

I recall we asked SMPTE to make some docs freely available and they graciously obliged; I don't remember offhand if this was in the set or not.

**Comment by svgeesus** [comment]
> SMPTE standards are now free for member

And for non-members?

**Comment by fintelia** [comment]
Yeah, "available for free after paying for a membership" just sounds like another way of saying "not freely available"

**Comment by svgeesus** [comment]
I see that SMPTE RP 2077 is now freely downloadable
  https://pub.smpte.org/latest/rp2077/rp2077-2013.pdf
