### ISSUE TITLE
Color metadata should be before image data

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#437]
[4.3 Color spaces](https://w3c.github.io/PNG-spec/#4Concepts.ColourSpaces) does not state this, but the individual chunks do. Thus, it should be stated as a general principle in this section.

**Comment by digitaltvguy** [comment]
> [4.3 Color spaces](https://w3c.github.io/PNG-spec/#4Concepts.ColourSpaces) does not state this, but the individual chunks do. Thus, it should be stated as a general principle in this section.

added proposed text below line 873 to specify a priority for color chunks and also added some detail to the alpha channel (being full range).

**Comment by svgeesus** [comment]
> added proposed text below line 873 to specify a priority for color chunks and also added some detail to the alpha channel (being full range).

Where did you do this?
