### ISSUE TITLE
Color space chunk precedence is repeated in a lot of places

### ISSUE THREAD

**Issue by fintelia** [w3c/PNG-spec#443]
Now that #439 added a table explaining the precedence of color space chunks, it would make sense to have the individual chunk descriptions link to it. Looking at the individual descriptions, none of them seem to be _wrong_, but the wording varies and it feels unnecessary to have this info repeated so many times.

All of this could be replaced with a line saying something like, "This chunk is ignored unless it is the highest-precedence color chunk [link] understood by the decoder."

---

cHRM:

> An <a class="chunk">sRGB</a>, <a class="chunk" >iCCP</a> or <a  class="chunk">cICP</a> chunk, when present and recognized, overrides the <span class="chunk">cHRM</span> chunk.

gAMA:

> An <a class="chunk" >sRGB</a>, <a class="chunk" >iCCP</a> or <a  class="chunk">cICP</a> chunk, when present and recognized, overrides the <span class="chunk">gAMA</span> chunk.

iCCP:

> When the <span class="chunk">iCCP</span> chunk is present, PNG decoders that recognize it and are capable of color management shall ignore the <a class="chunk" >gAMA</a> and <a class="chunk" >cHRM</a> chunks and use the <span class="chunk">iCCP</span> chunk instead and interpret it according to [[ICC]]. PNG decoders that are used in an environment that is incapable of full-fledged color management should use the <a class="chunk" >gAMA</a> and <a class="chunk" >cHRM</a> chunks if present.

sRGB:

> When the <span class="chunk">sRGB</span> chunk is present, it is recommended that decoders that recognize it and are capable of color management ignore the <a class="chunk" >gAMA</a> and <a class="chunk" >cHRM</a> chunks and use the <span class="chunk">sRGB</span> chunk instead. Decoders that recognize the <span class="chunk">sRGB</span> chunk but are not capable of color management are recommended to ignore the <a class="chunk" >gAMA</a> and <a class="chunk" >cHRM</a> chunks, and use the values given above as if they had appeared in <a class="chunk" >gAMA</a> and <a class="chunk" >cHRM</a> chunks.</p>

cICP:

> When the <span class="chunk">cICP</span> chunk is present, decoders that recognize it SHALL ignore the following chunks: iCCP, gAMA, cHRM, and sRGB

**Comment by ProgramMax** [comment]
Marking as '3rd edition' but I do not want this to block Third Edition. This is really just cleanup.
