### ISSUE TITLE
PNGv2 12.11.2 -> PNGv3 12.10.2 transcription issue

### ISSUE THREAD

**Issue by jbowler** [w3c/PNG-spec#446]
v2 12.11.2:

> 12.11.2 Private type and method codes
> This specification defines the meaning of only some of the possible values of some fields. For example, only compression method 0 and filter types 0 through 4 are defined in this International Standard. Numbers greater than 127 shall be used when inventing experimental or private definitions of values for any of these fields. Numbers below 128 are reserved for possible public extensions of this specification through future standardization (see 4.9 [Extension and registration](https://www.w3.org/TR/2003/REC-PNG-20031110/#4Concepts.Registration)). The use of private type codes may render a datastream unreadable by standard decoders. Such codes are strongly discouraged except for experimental purposes, and should not appear in publicly available software or datastreams.

Becomes v12.10.2:

>12.10.2 Use of non-reserved field values
>Encoders MAY use non-reserved field values for experimental or private use.

I feel this is excessive, but that's not an issue.  Rather the issue is the extra specification:

> 5.8 Private field values
> Values greater than or equal to 128 in the following fields are private field values:
> 
> [compression method](https://www.w3.org/TR/png-3/#10CompressionCM0)
> [interlace method](https://www.w3.org/TR/png-3/#8InterlaceMethods)
> [filter method](https://www.w3.org/TR/png-3/#9FtIntro)
> These [private field values](https://www.w3.org/TR/png-3/#dfn-private-field-values) are neither defined nor reserved by this specification.
> 
> [Private field values](https://www.w3.org/TR/png-3/#dfn-private-field-values) MAY be used for experimental or private semantics.
> 
> [Private field values](https://www.w3.org/TR/png-3/#dfn-private-field-values) SHOULD NOT appear in publicly available software or datastreams since they can result in datastreams that are unreadable by PNG decoders as detailed at [13. PNG decoders and viewers](https://www.w3.org/TR/png-3/#13Decoders).

So the bug of consequence is that this disallows private "color types" which were explicitly allowed in PNGv2; section 5.8 is new.

It also allows private big depth, which was not allowed before, but also it allows addition of compression method, filter method, filter type and interlace method without using the private bit flag (bit 7).  The bit flag is there to make it clear to everyone that this is a private, non-approved, extension/change.

**Comment by svgeesus** [comment]
Those changes come from

 - https://github.com/w3c/PNG-spec/pull/93

**Comment by jbowler** [comment]
> Probably best to say you need a private filter method if you want to add more filter types

"Filter method" and "filter type" are used interchangeably to refer to the value of the byte in the IHDR chunk.  This leads to endless confusion; within the libpng API definition (png.h) "filter_method" is used when setting/getting the IHDR values (this is a foolish consistency if ever there was one) but the API to get the value from a PNG that has been read is "png_get_filter_type".  The actual filter algorithm is not necessarily a single number; a new filter type/method might, for example, use different filter algorithms on different image channels.

In fact it's worse that that; the declaration of png_get_IHDR uses "method" throughout, the definition uses "type" throughout.  That has caused me considerably confusion at least once.

Nevertheless you are correct; MNG defines a value "64" to be used in the IHDR of a PNG which uses "intra-pixel differencing" for filtering.

Note that MNG uses a non-private value because the context (a PNG in a MNG stream) allows MNG to extend the public definitions.  The choice of "64" was to give some space so that PNG can separately add filter types without forcing MNG to fork the PNG spec (well, to stop taking updates...)

"Private" just means "all bets are off"; if a private value appears then it is necessary to look elsewhere for information about how to handle the stream.  For chunks this is a bit like XML; the chunk signature functions the same was as an XML schema, but a critical chunk, a signature change or, indeed, embedding in a different stream (as in MNG, which does all three) suffice.

In general my conclusions for private values in IHDR are that while any of the encoding control bytes (color type, bit depth, interlace method, compression method, filter type) can use private values I would put a critical chunk either before or immediate after the IHDR.  The latter, immediately after, I would do when just changing compression method or filter type because those changes don't alter the canonical frame-buffer format; an _application_ does not need to concern itself with compression method or filter type because the _library_ handles that.  It does need to take action if it gets a color type or a bit depth or, indeed, an interlace method that it doesn't support.

BTW I see no problem with lying; PNG supports "RGB" or "luminance" data with an option per-pixel coverage value.  Well, ok, if I have YCbCr I can change the filter type or the compression method to say that and I can still decode it to RGB.  If my luma channel has 14 bits then I can still decode that to RGB 16-bit channels.  If my coverage channel has only 3-bits (all that is required) I can still produce 8 if you really must have that :-)  If I have an OpenEXR with (RA,GA,BA) and a depth map too that's just a different filter type and, if you're me, compression method.  You can't take the private bit away from me.
