### ISSUE TITLE
Call for Consensus: publish Candidate Recommendation

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#453]
This GitHub issue is to establish consensus on publishing a Candidate Recommendation. W3C Working Group participants should reply with affirmation, dissent, or may abstain.

Should we publish a Candidate Recommendation?

Process
[Consensus is a core value to the W3C.](https://www.w3.org/2021/Process-20211102/#Consensus) I have assigned this issue to all [PNG WG participants who have their GitHub profile listed](https://www.w3.org/groups/wg/png/participants). Said Abou-Hallawa and Fares Alhassen do not have a GitHub account listed. I will try to email them.

A WG participant may register a [Formal Objection](https://www.w3.org/2021/Process-20211102/#FormalObjection) if they would like Director consideration.

WG participants may respond with a simple yes/no or similar. They may also elaborate. If dissenting, elaboration is encouraged in order to identify issues and find solutions. The [W3C process on managing dissent](https://www.w3.org/2021/Process-20211102/#managing-dissent) states that we will try to address concerns as much as is reasonable and should move on once that is done.

Call to action
Working group participants should reply with their stance on publishing a Candidate Recommendation.

**Comment by annevk** [comment]
My main concern is that we still have very few tests, which might mean certain aspects have to be revisited as it becomes more clear what is actually implemented.

**Comment by ProgramMax** [comment]
@annevk We have tests for each green/red box listed in [the Implementation Report](https://w3c.github.io/PNG-spec/Implementation_Report_3e/index.html). It covers each change that is testable (some cannot be).

Are there some we missed?

**Comment by svgeesus** [comment]
> My main concern is that we still have very few tests, which might mean certain aspects have to be revisited as it becomes more clear what is actually implemented.

True, but remember this is the Third Edition. At this point, except for ambiguities pointed out in errata reports, we are not testing things that are unchanged from the First or Second editions.

I certainly agree that those should be tested too, but adding those tests is not the current priority.

**Comment by svgeesus** [comment]
Yes, lets publish an updated CR.

**Comment by digitaltvguy** [comment]
I vote yes.

**Comment by chrisn** [comment]
+1 to publishing an updated CR

**Comment by leo-barnes** [comment]
I abstain.
@hober and @annevk has been following the changes much more closely than me and can vote for Apple.

**Comment by shallawa** [comment]
I abstain too.
@hober and @annevk has been following the changes much more closely than me and can vote for Apple.

**Comment by svgeesus** [comment]
@palemieux @lrosenthol @ccameron-chromium

**Comment by svgeesus** [comment]
> as it becomes more clear what is actually implemented.

@annevk Speaking of, there are six APNG tests which [fail in WebKit but pass in Blink and in Gecko](https://wpt.fyi/results/png/apng?label=master&label=experimental&aligned) who should we be talking to to have those bugs reported and fixed?

**Comment by ProgramMax** [comment]
@annevk Any chance you'll be able to join the meeting tomorrow to discuss what test coverage we should improve?
Or if you cannot join tomorrow, can you give more info here?

**Comment by simontWork** [comment]
+1 to publishing an updated CR

**Comment by palemieux** [comment]
+1 to publishing the CR

**Comment by ProgramMax** [comment]
The votes thus far are:
6 yes
2 abstain
1 concern, which we're trying to address

5 people have not yet voted. @hober @podborski (who I forgot to assign to originally, sorry), @lrosenthol Fares (who I'll ping in email again), @ccameron-chromium 

I'll give this a bit more time.

**Comment by podborski** [comment]
I also abstain.
@hober and @annevk has been following the changes much more closely than me and can vote for Apple.

**Comment by annevk** [comment]
Apologies, my concern was not meant to be blocking.

+1 to publishing the CR (also on behalf of @hober).

**Comment by ProgramMax** [comment]
Ah. Good to hear. :D That changes the equation a bit.
That makes it 8 yes, 3 abstain, and 3 not yet voted.
With that, I'll consider consensus reached. We'll publish a new Candidate Recommendation.

**Comment by ProgramMax** [comment]
Fares replied to me via email after this. His stance is abstain.

**Comment by lrosenthol** [comment]
+1 to publishing

**Comment by ccameron-chromium** [comment]
ccameron abstains

**Comment by svgeesus** [comment]
[CR Snapshot update request](https://github.com/w3c/transitions/issues/636)
