### ISSUE TITLE
cICP should not appear?

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#56]
```html
<p>It is recommended that the <span class="chunk">cICP</span> chunk does not appear in a
PNG datastream.</p>
```

What? Should this be something like 

```html
<p>It is recommended that the <span class="chunk">iCCP</span> chunk does not appear in a
PNG datastream if <span class="chunk">cICP</span> is present.</p>
```

**Comment by digitaltvguy** [comment]
I assumed this was suggesting that cICP chunk should ideally be in the header so the entire file doesn't have to be scanned to read it in the stream.  Was this incorrect?

**Comment by svgeesus** [comment]
Ah, I see. Yes.

[The PNG datastream consists of a PNG signature (see 5.2: PNG signature) followed by a sequence of chunks (see clause 11: Chunk specifications). Each chunk has a chunk type which specifies its function.](https://w3c.github.io/PNG-spec/#4Concepts.Format_)

So this is saying "do not put cICP in PNG" :)

You already have "The cICP chunk should come before the IDAT chunk." Which covers it, though I would be tempted to boost that "should" to a "must".

**Comment by digitaltvguy** [comment]
I’ve updated based on your suggestions.  Thx!

From: Chris Lilley ***@***.***>
Date: Friday, December 17, 2021 at 10:23 AM
To: w3c/PNG-spec ***@***.***>
Cc: Seeger, Chris (NBCUniversal) ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [w3c/PNG-spec] cICP should not appear? (Issue #56)

Ah, I see. Yes.

The PNG datastream consists of a PNG signature (see 5.2: PNG signature) followed by a sequence of chunks (see clause 11: Chunk specifications). Each chunk has a chunk type which specifies its function.<https://urldefense.com/v3/__https:/w3c.github.io/PNG-spec/*4Concepts.Format___;Iw!!PIZeeW5wscynRQ!578yBj5CZb8gLALRwH3204lXp9YkoavbnW33t3sZndb_Nlvc7NQpSMCaBDUoQqPOcA$>

So this is saying "do not put cICP in PNG" :)

You already have "The cICP chunk should come before the IDAT chunk." Which covers it, though I would be tempted to boost that "should" to a "must".
