### ISSUE TITLE
Where to find current list of registered extensions ?

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#8]
Raised by: david
Originally raised: [24 Oct 2007](https://lists.w3.org/Archives/Public/png-group/2007Oct/0000.html)

> where to find list of current chunk type alternative extensions ?

**Comment by svgeesus** [comment]
Also raised by: Adrian Custer
Original date: [12 Jun 2012](https://lists.w3.org/Archives/Public/png-group/2012Jun/0000.html)

> This email therefore is asking you for the canonical reference to the
registered extensions. 

> My first question is where one can find the authoritative list of the
'chunks' which are currently registered in the registry given in section
4.9 of the standard: 
  http://www.w3.org/TR/PNG/#4Concepts.Registration
The closest source I have found is the document:
  Register of public PNG chunks and keywords, Version 1.4.5
  ftp://ftp.simplesystems.org/pub/png/documents/pngreg-1.4.5-pdg.html
Is that the formal list?

**Comment by Crissov** [comment]
[PNG Extension Registry](http://www.libpng.org/pub/png/spec/register/)

* `fRAc`, `gIFg`, `gIFt`, `gIFx`, `oFFs`, `sCAL` 1995-03-07 PNGEXT 1.2.0
* `pCAL` 1997-01-28 PNGEXT 1.2.0
* `sTER` 2006-04-15 PNGEXT 1.3.0
* `dSIG` 2008-05-01 PNGEXT 1.4.0

**Comment by ProgramMax** [comment]
This question has been well answered. But I don't think this issue should be closed.
Rather, I think we should update [4.9 Extension and registration](https://www.w3.org/TR/PNG/#4Concepts.Registration) with information about where to find currently registered extensions. Right now, it only specifies how to register new extensions.

The spec does have [PNG-REGISTER] already. I think a link to that should be added to 4.9.

**Comment by svgeesus** [comment]
It makes sense to put a list of registered (but non-standard) extensions on the W3C site rather than pointing off to a dead list that is no longer maintained.

I agree that the existing Extension and registration section should be updated to point to this.

Note that W3C now has [a Registry Track](https://www.w3.org/2021/Process-20211102/#registries) in addition to the [Recommendation Track](https://www.w3.org/2021/Process-20211102/#rec-track) but so far, I have no experience with it. Florian Rivoal made some [useful slides about registries at W3C](https://www.w3.org/2020/10/TPAC/talk/Process2021#talk) although those pre-date adoption of the registries proposal.

**Comment by svgeesus** [comment]
The list in [Register of public PNG chunks and keywords, Version 1.4.6](http://www.libpng.org/pub/png/spec/register/pngreg-1.4.6-pdg.html) doesn't really add much - it is a union of the standard chunks plus the other registered chunks.

The [Extensions to the PNG 1.2 Specification, Version 1.4.0](http://www.libpng.org/pub/png/spec/register/pngext-1.4.0-pdg.html) has useful detail, although it would be interesting to know if any of those special-purpose chunks are actually used.

Oh wait there is a newer list [Extensions to the PNG 1.2 Specification, Version 1.5.0](http://ftp-osl.osuosl.org/pub/libpng/documents/pngext-1.5.0.html) and [Register of public PNG chunks and keywords, Version 1.5.0](http://ftp-osl.osuosl.org/pub/libpng/documents/pngreg-1.5.0.html)

**Comment by svgeesus** [comment]
Given that we plan to add three new chunks, and move one from the extensions to the main spec, it seems we should have our own registry as the 1.5.0 document is unlikely to be updated.

**Comment by svgeesus** [comment]
[PR for first draft of the chunk and keyword registry](https://github.com/w3c/PNG-spec/pull/37)

**Comment by svgeesus** [comment]
TODO: I notice that the `pCAL` date [given by @Crissov](https://github.com/w3c/PNG-spec/issues/8#issuecomment-827125058) (1997-01-28) is different to the one in the 1.5.0 Register of public chunks and keywords (28 Jan 1997)

**Comment by svgeesus** [comment]
[Pubrules requirements for Draft Registry](https://www.w3.org/pubrules/doc/rules/?profile=DRY)

**Comment by ProgramMax** [comment]
> It makes sense to put a list of registered (but non-standard) extensions on the W3C site rather than pointing off to a dead list that is no longer maintained.

I agree that it would be wise for us to maintain the spec and registry side by side.


> it would be interesting to know if any of those special-purpose chunks are actually used.

Back when I worked at Google, I could gather data about how often various PNG chunks are used.
I can still write those changes and ask a current Googler to provide that information back to us after it is gathered, if they're allowed.

Do you say it would be good to know how often chunks are used because perhaps we should deprecate some?
(I personally strongly favor deprecating and removing old things. But on the web, that might be difficult.)

**Comment by svgeesus** [comment]
Here is the [converted registry](https://w3c.github.io/PNG-spec/registry/Overview.html).

It is a simple table of chunks, followed by a table of keywords.

To be honest the main work for me here was making the html of the document pass the W3C rules for a registry. The actual tables are super simple.

I want to make them point to their actual definition. But I will need to convert the extensions document, first.

**Comment by Crissov** [comment]
In the entry for the _Collection_ keyword, the century is missing in `24 Jul 04`.

**Comment by svgeesus** [comment]
Here is the [PNG Extensions document](https://w3c.github.io/PNG-spec/extensions/Overview.html).

I converted it to Bikeshed format for ease of maintenance: the source file is `extensions/Overview.bs`
