### ISSUE TITLE
Use proper bibliographic references

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#82]
The normative and informative references are hard-coded rather than [bibliographic references](https://respec.org/docs/#references) using [SpecRef](https://github.com/tobie/specref). Also, the normative ones are at the top of the document and the informative ones are at the end, listed as "Bibliography".

 - [x] Convert all inline references
 - [x] Make [local biblioref](https://respec.org/docs/#localBiblio) for any missing ones
 - [x] Collect these into normative and informative references
 - [x] Delete the hardcoded sections
 - [ ] Submit missing ones to SpecRef database

**Comment by svgeesus** [comment]
For "convert all inline references" see https://github.com/w3c/PNG-spec/pull/85

**Comment by svgeesus** [comment]
PR was merged.

Next step is to find where all the informative references are mentioned, trim any that are not in fact referenced, and turn those that are into SpecRef references

**Comment by ProgramMax** [comment]
This is something I don't yet know. I should probably learn this.
Is there a W3C database of these SpecRef references where I should suggest additions? Is it something only available to W3C people and so I don't need to worry about it?

**Comment by svgeesus** [comment]
The database used by both ReSpec and Bikeshed is [SpecRef](https://github.com/tobie/specref) which started as W3C-oriented but is used by other standards organizations as well.

**Comment by svgeesus** [comment]
See https://github.com/w3c/PNG-spec/pull/133

**Comment by ProgramMax** [comment]
The 4th work item on this is "Delete the hardcoded sections".
@svgeesus and @palemieux, is this fixed as of #106?
