### ISSUE TITLE
Out-of-range palette indices

### ISSUE THREAD

**Issue by randy408** [w3c/PNG-spec#96]
For indexed color images the following rule applies to PLTE:

[11.2.3 PLTE Palette](https://www.w3.org/TR/2003/REC-PNG-20031110/#11PLTE)

> ... It is permissible to have fewer entries than the bit depth would allow. In that case, any out-of-range pixel value found in the image data is an error.

By default libpng does not handle out-of-range values as an error, instead they're interpreted as black pixels. If the output format has an alpha channel the maximum alpha value (fully opaque) is assumed.

The first attached image is a 128x128 8-bit indexed color image with gray borders, the 3 palette entries are: white, gray and blue in that order.
Only the gray and blue entries are used from the palette but black shows up in the image which is not part of the palette. The bottom half is blue and the top half is filled with invalid values (`100`), this part is black even though the first palette entry is white, it is not defaulting to the first entry or anything like that.

![index](https://user-images.githubusercontent.com/33860634/154865703-daa7c36a-3546-4a8c-a964-359330d9ddef.png)

The second image is the same but a tRNS chunk was added with 3 entries, the alpha values are 0, 255, 0 meaning the blue part should be transparent (and it is). This is just to show that when an alpha channel is added the part with out-of-range values will always be black and opaque, regardless of transparency values.

![index](https://user-images.githubusercontent.com/33860634/154865854-7aa4991b-d3a2-4731-be85-54f2e7d89c77.png)

Should this be standardized to prevent more alternative and incompatible behaviors? Instead of saying it's an error it could be a choice between treating them as black, opaque pixels OR as an error.

**Comment by ProgramMax** [comment]
> Should this be standardized...?

In my opinion, yes. I think a spec should be crystal clear about what should happen in every foreseeable scenario. An exception is when undefined behavior allows for a benefit. But I can't think of when this might apply to image encoding / decoding.

Interestingly, gif has a similar scenario. But unfortunately, it works in the other direction.
The gif spec says there should never be an index that is outside the palette. Of course, it can happen. Somewhere along the lines, indices outside of the palette range were treated as transparent. And then several gifs began to rely on this as a free extra palette slot. (Gif uses a palette entry for transparent. There is no alpha channel.)

Many gif decoders share this same behavior, even though it isn't actually part of the spec. I've been calling this part of the "street spec".

We should look at several PNG decoders to see if they all treat it the same way, and have a "street spec". It looks like Chromium-based browsers and Firefox have the same behavior.

**Comment by ProgramMax** [comment]
Do you happen to know if there are decoders that treat this differently? Are there images in the wild that rely on this?

During the PNG WG meeting yesterday, a point was made that if there is no real world problem then the best action is to not over-specify. It would be spending energy (and making some decoders non-compliant) with no benefit.

We could add a note to the spec that mentions such a scenario should not happen but is nevertheless possible, and here are how various decoders have handled it in the past.

Perhaps here we could add a note that there is a common behavior but it is not a required part of the spec. Since the image itself is not standard compliant the image risks being decoded in unintended ways.

(This is opposed to things like quirks mode in browsers, where there was already wide-spread usage. And it would be interesting to hear from a security expert about potential covert messages and if that matters.)

**Comment by randy408** [comment]
Some quick tests show libpng, lodepng and spng all produce the same data for both images when the output format is 8-bit RGBA, for stb_image the invalid region is transparent instead of opaque so it's not consistent across the board.

I discovered this a few years ago (https://github.com/randy408/libspng/commit/4955d6449b8fd62083b924c973461687888857dc) and don't remember which file triggered it. At the time I wasn't crafting PNG's for testing, it was probably an image from the wild.

> Perhaps here we could add a note that there is a common behavior but it is not a required part of the spec. 

I agree with this approach. It's a lot easier for implementors to handle these corner cases when it's spelled out somewhere, even if it's not a requirement.

A more concrete example of why implementation notes are needed is the handling of (extra) trailing image data. Both spng (https://github.com/randy408/libspng/commit/db54f219411b5da2f9bebfa4c320c5a7b6b17040) and stb_image (https://github.com/nothings/stb/pull/475) had to be patched because that part is also under-specified. The [PngSuite](http://www.schaik.com/pngsuite/) is full of these (probably unintentional, but not mentioned anywhere) and the patch to stb_image was prompted by an image in the wild. The reference implementation ignores trailing data silently.
It's too late to disallow trailing data or to require decoders to ignore it but it would definitely reduce the trial-and-error nature of implementing a decoder if the specification had notes on these details.

**Comment by ProgramMax** [comment]
@randy408 I am really glad you're here. :) You've contributed some great insight into these GitHub issues.
Out of curiosity, would you be interested in sending some pull requests, too?

**Comment by ProgramMax** [comment]
I created #158 to be a separate place to discuss and track the trailing bytes. Let's keep this issue specifically about out-of-range palette indices.

**Comment by ProgramMax** [comment]
In the Aug 8th, 2022 meeting we agreed to be firm about PNG encoders to not do this. But we will also add a note for PNG decoders that there are images in the wild which abuse this and different decoders behave differently when they encounter these images. (This further discourages PNG encoders.)

**Comment by svgeesus** [comment]
This one isn't quite as simple, because [13.1 Error handling](https://w3c.github.io/PNG-spec/#13Decoders.Errors) encourages "recover from an error, if possible". So I think the "some decoders handle out of range index entries like this" needs to be framed as error recovery.

Phrasing it as one approach gives guidance, while discouraging relying on the behavior.

**Comment by svgeesus** [comment]
I think we can elevate this to a requirement, at least for web browsers. Safari, Chrome and Firefox all display as opaque black.

Change:

```html
<p>When decoding an indexed-color PNG, if out-of-range indexes are encountered,
  decoders have historically varied in their handling of this error.
  Displaying the pixel as opaque black is one common error recovery tactic,
  although such behaviour is not required by this specification
  and must not be relied on by encoders.
</p>
```

to

```html
<p>When decoding an indexed-color PNG, if out-of-range indexes are encountered,
  decoders have historically varied in their handling of this error.
  Displaying the pixel as opaque black is one common error recovery tactic,
  and is now required by this specification.
  Older implementations will vary, and so the behavior
 must not be relied on by encoders.
</p>
```

**Comment by svgeesus** [comment]
Interestingly Facebook Messenger link preview does not and goes for some greyish pink instead 

![image](https://github.com/w3c/PNG-spec/assets/2506926/f9229fb3-6d02-4f0b-900b-f4f017b404e1)

**Comment by svgeesus** [comment]
I raised [a bug on Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1862235) for handling out of range palette indexes in `tRNS`. We have [a WPT for that](https://wpt.fyi/results/png/trns-chunk.html?label=master&label=experimental&aligned) which is passed in Chrome, Edge and Safari but currently fails in Firefox.
